# Subsidiary Data Analysis
Analyze parsed subsidiary data from SEC filings

## 0. Setup

In [13]:
import polars as pl
from pathlib import Path

pl.Config.set_tbl_rows(100)
pl.Config.set_fmt_str_lengths(200)

# Load CSVs
success_csv = Path("../../../../subsidiaries_SUCCESS.csv")
empty_csv = Path("../../../../subsidiaries_EMPTY.csv")

df = pl.read_csv(success_csv, schema_overrides={"Ownership": pl.Float64})
df_empty = pl.read_csv(empty_csv)

print(f"Total rows (success): {len(df):,}")
print(f"Columns: {df.columns}")

# Count unique accessions
unique_accessions = df["Accession"].n_unique()
unique_empty_accessions = df_empty["Accession"].n_unique()

print(f"\nTotal filings processed: {unique_accessions + unique_empty_accessions:,}")
print(f"- Unique accessions (with subsidiaries): {unique_accessions:,}")
print(f"- Unique accessions (empty): {unique_empty_accessions:,}")


df_empty.head(10)

Total rows (success): 47,735
Columns: ['Accession', 'URL', 'SubsidiaryId', 'Subsidiary', 'Jurisdiction', 'NestingLevel', 'ParentName', 'ParentId', 'Ownership', 'Footnotes']

Total filings processed: 466
- Unique accessions (with subsidiaries): 428
- Unique accessions (empty): 38

shape: (10, 2)
┌─────────────────────┬────────────────────────────────────────────────────────────────────────────┐
│ Accession           ┆ URL                                                                        │
│ ---                 ┆ ---                                                                        │
│ str                 ┆ str                                                                        │
╞═════════════════════╪════════════════════════════════════════════════════════════════════════════╡
│ `000003799625000013 ┆ https://www.sec.gov/Archives/edgar/data/37996/000003799625000013/f12312024 │
│                     ┆ exhibit21.htm                                                              │
│ `000105955625000025 ┆ https://www.sec.gov/Archives/edgar/data/1059556/000105955625000025/mco-202 │
│                     ┆ 41231xexx21.htm                                                            │
│ `000006008625000036 ┆ https://www.sec.gov/Archives/edgar/data/60086/000006008625000036/exhibit21 │
│                     ┆ 01-q42024.htm                                                              │
│ `000155115225000020 ┆ https://www.sec.gov/Archives/edgar/data/1551152/000155115225000020/abbv-20 │
│                     ┆ 241231xex21.htm                                                            │
│ `000162828025005100 ┆ https://www.sec.gov/Archives/edgar/data/943452/000162828025005100/wabex210 │
│                     ┆ -10k2024.htm                                                               │
│ `000175178825000012 ┆ https://www.sec.gov/Archives/edgar/data/1751788/000175178825000012/dowinc2 │
│                     ┆ 02410kex21.htm                                                             │
│ `000093646825000009 ┆ https://www.sec.gov/Archives/edgar/data/936468/000093646825000009/ex21q420 │
│                     ┆ 24.htm                                                                     │
│ `000141344725000019 ┆ https://www.sec.gov/Archives/edgar/data/1413447/000141344725000019/a211lis │
│                     ┆ tofsubsidiaries20.htm                                                      │
│ `000107173925000027 ┆ https://www.sec.gov/Archives/edgar/data/1071739/000107173925000027/a202412 │
│                     ┆ 3110-kexhibit21.htm                                                        │
│ `000113778925000157 ┆ https://www.sec.gov/Archives/edgar/data/1137789/000113778925000157/stx-ex2 │
│                     ┆ 11_20250627.htm                                                            │
└─────────────────────┴────────────────────────────────────────────────────────────────────────────┘

In [14]:
# Query rows for a specific accession
accession_to_find = "`000106770125000008"
df.filter(pl.col("Accession") == accession_to_find)

shape: (4, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Accession ┆ URL       ┆ Subsidiar ┆ Subsidiar ┆ … ┆ ParentNam ┆ ParentId  ┆ Ownership ┆ Footnote │
│ ---       ┆ ---       ┆ yId       ┆ y         ┆   ┆ e         ┆ ---       ┆ ---       ┆ s        │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ f64       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ `00010677 ┆ https://w ┆ 65bf51a8- ┆ UNITED    ┆ … ┆ UNITED    ┆ 65bf51a8- ┆ null      ┆          │
│ 012500000 ┆ ww.sec.go ┆ 6f5f-5983 ┆ RENTALS   ┆   ┆ RENTALS,  ┆ 6f5f-5983 ┆           ┆          │
│ 8         ┆ v/Archive ┆ -b70a-ee9 ┆           ┆   ┆ INC.      ┆ -b70a-ee9 ┆           ┆          │
│           ┆ s/edgar/d ┆ 8d81d2410 ┆           ┆   ┆           ┆ 8d81d2410 ┆           ┆          │
│           ┆ ata/10677 ┆ -sub-1    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 01/000106 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 770125000 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 008/uri-2 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 024123110 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ kex21.htm ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ `00010677 ┆ https://w ┆ 65bf51a8- ┆ Incorpora ┆ … ┆ UNITED    ┆ 65bf51a8- ┆ null      ┆          │
│ 012500000 ┆ ww.sec.go ┆ 6f5f-5983 ┆ tion      ┆   ┆ RENTALS,  ┆ 6f5f-5983 ┆           ┆          │
│ 8         ┆ v/Archive ┆ -b70a-ee9 ┆           ┆   ┆ INC.      ┆ -b70a-ee9 ┆           ┆          │
│           ┆ s/edgar/d ┆ 8d81d2410 ┆           ┆   ┆           ┆ 8d81d2410 ┆           ┆          │
│           ┆ ata/10677 ┆ -sub-2    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 01/000106 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 770125000 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 008/uri-2 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 024123110 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ kex21.htm ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ `00010677 ┆ https://w ┆ 65bf51a8- ┆ (a)       ┆ … ┆ UNITED    ┆ 65bf51a8- ┆ null      ┆          │
│ 012500000 ┆ ww.sec.go ┆ 6f5f-5983 ┆ United    ┆   ┆ RENTALS,  ┆ 6f5f-5983 ┆           ┆          │
│ 8         ┆ v/Archive ┆ -b70a-ee9 ┆ Rentals   ┆   ┆ INC.      ┆ -b70a-ee9 ┆           ┆          │
│           ┆ s/edgar/d ┆ 8d81d2410 ┆ Asia      ┆   ┆           ┆ 8d81d2410 ┆           ┆          │
│           ┆ ata/10677 ┆ -sub-3    ┆ Pacific   ┆   ┆           ┆           ┆           ┆          │
│           ┆ 01/000106 ┆           ┆ Holdings  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 770125000 ┆           ┆ Pty Ltd   ┆   ┆           ┆           ┆           ┆          │
│           ┆ 008/uri-2 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 024123110 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ kex21.htm ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ `00010677 ┆ https://w ┆ 65bf51a8- ┆ B.        ┆ … ┆ UNITED    ┆ 65bf51a8- ┆ null      ┆          │
│ 012500000 ┆ ww.sec.go ┆ 6f5f-5983 ┆ Harbor    ┆   ┆ RENTALS,  ┆ 6f5f-5983 ┆           ┆          │
│ 8         ┆ v/Archive ┆ -b70a-ee9 ┆ Point     ┆   ┆ INC.      ┆ -b70a-ee9 ┆           ┆          │
│           ┆ s/edgar/d ┆ 8d81d2410 ┆ Insurance ┆   ┆           ┆ 8d81d2410 ┆           ┆          │
│           ┆ ata/10677 ┆ -sub-4    ┆ Company   ┆   ┆           ┆           ┆           ┆          │
│           ┆ 01/000106 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 770125000 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 008/uri-2 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 024123110 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ kex21.htm ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
# Find rows with empty or null jurisdiction
empty_jurisdiction = df.filter(
    pl.col("Jurisdiction").is_null() | (pl.col("Jurisdiction").str.strip_chars() == "")
)

unique_accessions = empty_jurisdiction.select("Accession").unique()
print(f"Rows with empty jurisdiction: {len(empty_jurisdiction):,}")

print(f"\nUnique accession list({len(unique_accessions)}): ")
print(unique_accessions.to_series().to_list())
empty_jurisdiction.head(10)

Rows with empty jurisdiction: 0

Unique accession list(0):
[]

shape: (0, 10)
┌───────────┬─────┬──────────────┬────────────┬───┬────────────┬──────────┬───────────┬───────────┐
│ Accession ┆ URL ┆ SubsidiaryId ┆ Subsidiary ┆ … ┆ ParentName ┆ ParentId ┆ Ownership ┆ Footnotes │
│ ---       ┆ --- ┆ ---          ┆ ---        ┆   ┆ ---        ┆ ---      ┆ ---       ┆ ---       │
│ str       ┆ str ┆ str          ┆ str        ┆   ┆ str        ┆ str      ┆ f64       ┆ str       │
╞═══════════╪═════╪══════════════╪════════════╪═══╪════════════╪══════════╪═══════════╪═══════════╡
└───────────┴─────┴──────────────┴────────────┴───┴────────────┴──────────┴───────────┴───────────┘

## 1. Nested Subsidiaries (NestingLevel >= 1)

In [16]:
# Find nested subsidiaries
nested = df.filter(pl.col("NestingLevel") >= 1)

nested_accessions = nested.select("Accession").unique()
print(f"Nested subsidiaries (level >= 1): {len(nested):,}")

print(f"Unique accession list({len(nested_accessions)}):")
print(nested_accessions.to_series().to_list())
# nested.head(20)


# Filter by specific accession
pl.Config.set_tbl_rows(-1) 
target_accession = '`000007889025000059'
df.filter(pl.col("Accession") == target_accession)

Nested subsidiaries (level >= 1): 318
Unique accession list(10):
['`000008066125000007', '`000111316925000007', '`000000428125000011', '`000010781525000103', '`000005114325000015', '`000086073125000007', '`000133692025000006', '`000162828025056742', '`000001961725000270', '`000089542125000304']

shape: (0, 10)
┌───────────┬─────┬──────────────┬────────────┬───┬────────────┬──────────┬───────────┬───────────┐
│ Accession ┆ URL ┆ SubsidiaryId ┆ Subsidiary ┆ … ┆ ParentName ┆ ParentId ┆ Ownership ┆ Footnotes │
│ ---       ┆ --- ┆ ---          ┆ ---        ┆   ┆ ---        ┆ ---      ┆ ---       ┆ ---       │
│ str       ┆ str ┆ str          ┆ str        ┆   ┆ str        ┆ str      ┆ f64       ┆ str       │
╞═══════════╪═════╪══════════════╪════════════╪═══╪════════════╪══════════╪═══════════╪═══════════╡
└───────────┴─────┴──────────────┴────────────┴───┴────────────┴──────────┴───────────┴───────────┘

In [17]:
# Distribution of nesting levels
df.group_by("NestingLevel").agg(pl.count().alias("count")).sort("NestingLevel")

/var/folders/pg/rrvt9fgx479brk1wjwzw9bqc0000gn/T/ipykernel_34712/269099081.py:2: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  df.group_by("NestingLevel").agg(pl.count().alias("count")).sort("NestingLevel")

shape: (5, 2)
┌──────────────┬───────┐
│ NestingLevel ┆ count │
│ ---          ┆ ---   │
│ i64          ┆ u32   │
╞══════════════╪═══════╡
│ 0            ┆ 47417 │
│ 1            ┆ 267   │
│ 2            ┆ 37    │
│ 3            ┆ 11    │
│ 4            ┆ 3     │
└──────────────┴───────┘

In [18]:
# TODO: Find parent rows based on ParentId = SubsidiaryId
# (Commented out - we don't have SubsidiaryId column yet)

# nested_with_parents = nested.join(
#     df.select(["SubsidiaryId", "Subsidiary", "Jurisdiction"]).rename({"Subsidiary": "ParentSubsidiary", "Jurisdiction": "ParentJurisdiction"}),
#     left_on="ParentId",
#     right_on="SubsidiaryId",
#     how="left"
# )
# nested_with_parents

## 2. Rows with Footnotes

In [19]:
# Find rows with non-empty footnotes
with_footnotes = df.filter(
    pl.col("Footnotes").is_not_null() & (pl.col("Footnotes").str.strip_chars() != "")
)

footnotes_accessions = with_footnotes.select("Accession").unique()

print(f"Rows with footnotes: {len(with_footnotes):,}")
print(f"Percentage: {len(with_footnotes) / len(df) * 100:.1f}%")

print(f"\nUnique Accession list({len(footnotes_accessions)}):")
print(footnotes_accessions.to_series().to_list())
with_footnotes.head(20)

Rows with footnotes: 382
Percentage: 0.8%

Unique Accession list(37):
['`000000497725000047', '`000138119725000036', '`000132440425000006', '`000076447825000007', '`000109921925000044', '`000007747625000007', '`000089905125000015', '`000093570325000015', '`000003408825000010', '`000155837025001222', '`000031920125000024', '`000155837025001263', '`000087721225000027', '`000162828025037656', '`000105350725000025', '`000128176125000010', '`000010416925000021', '`000171126925000004', '`000001154425000005', '`000004054525000015', '`000151029525000012', '`000005125325000013', '`000006270925000015', '`000162828025007110', '`000155837025003413', '`000007736025000006', '`000000248825000012', '`000162828025006093', '`000087532025000053', '`000085973725000072', '`000139718725000013', '`000112336025000011', '`000095017025024750', '`000119312525034579', '`000199681025000011', '`000008980025000030', '`000162828025005715']

shape: (20, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Accession ┆ URL       ┆ Subsidiar ┆ Subsidiar ┆ … ┆ ParentNam ┆ ParentId  ┆ Ownership ┆ Footnote │
│ ---       ┆ ---       ┆ yId       ┆ y         ┆   ┆ e         ┆ ---       ┆ ---       ┆ s        │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ f64       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ `00017112 ┆ https://w ┆ f61e0379- ┆ Name of   ┆ … ┆ Evergy,   ┆ f61e0379- ┆ null      ┆ 2        │
│ 692500000 ┆ ww.sec.go ┆ 7c43-5837 ┆ CompanySt ┆   ┆ Inc.      ┆ 7c43-5837 ┆           ┆          │
│ 4         ┆ v/Archive ┆ -800f-7fc ┆ ate of    ┆   ┆           ┆ -800f-7fc ┆           ┆          │
│           ┆ s/edgar/d ┆ e7d76a27d ┆ Incorpora ┆   ┆           ┆ e7d76a27d ┆           ┆          │
│           ┆ ata/17112 ┆ -sub-1    ┆ tionEverg ┆   ┆           ┆           ┆           ┆          │
│           ┆ 69/000171 ┆           ┆ y Metro,  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 126925000 ┆           ┆ Inc.Misso ┆   ┆           ┆           ┆           ┆          │
│           ┆ 004/evrg- ┆           ┆ uriEvergy ┆   ┆           ┆           ┆           ┆          │
│           ┆ 12312024x ┆           ┆ Missouri  ┆   ┆           ┆           ┆           ┆          │
│           ┆ ex211.htm ┆           ┆ West, Inc ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ .Delaware ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Evergy    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Kansas    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Central,  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Inc.Kansa ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ sEvergy   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Kansas    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ South     ┆   ┆           ┆           ┆           ┆          │
│ `00017112 ┆ https://w ┆ f61e0379- ┆ Evergy    ┆ … ┆ Evergy,   ┆ f61e0379- ┆ null      ┆ 2        │
│ 692500000 ┆ ww.sec.go ┆ 7c43-5837 ┆ Kansas    ┆   ┆ Inc.      ┆ 7c43-5837 ┆           ┆          │
│ 4         ┆ v/Archive ┆ -800f-7fc ┆ South     ┆   ┆           ┆ -800f-7fc ┆           ┆          │
│           ┆ s/edgar/d ┆ e7d76a27d ┆           ┆   ┆           ┆ e7d76a27d ┆           ┆          │
│           ┆ ata/17112 ┆ -sub-2    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 69/000171 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 126925000 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 004/evrg- ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 12312024x ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ex211.htm ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ `00017112 ┆ https://w ┆ f61e0379- ┆ Evergy    ┆ … ┆ Evergy,   ┆ f61e0379- ┆ null      ┆ 2        │
│ 692500000 ┆ ww.sec.go ┆ 7c43-5837 ┆ Kansas    ┆   ┆ Inc.      ┆ 7c43-5837 ┆           ┆          │
│ 4         ┆ v/Archive ┆ -800f-7fc ┆ South,    ┆   ┆           ┆ -800f-7fc ┆           ┆          │
│           ┆ s/edgar/d ┆ e7d76a27d ┆ Inc. is a ┆   ┆           ┆ e7d76a27d ┆           ┆          │
│           ┆ ata/17112 ┆ -sub-3    ┆ subsidiar ┆   ┆           ┆           ┆           ┆          │
│           ┆ 69/000171 ┆           ┆ y of      ┆   ┆           ┆           ┆           ┆          │
│           ┆ 126925000 ┆           ┆ Evergy    ┆   ┆           ┆           ┆           ┆          │
│           ┆ 004/evrg- ┆           ┆ Kansas    ┆   ┆           ┆           ┆           ┆          │
│           ┆ 12312024x ┆           ┆ Central   ┆   ┆           ┆           ┆           ┆          │
│           ┆ ex211.htm ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ `00000898 ┆ https://w ┆ 746e8aad- ┆ 1 The She ┆ … ┆ SHERWIN   ┆ 746e8aad- ┆ null      ┆ 3        │
│ 002500003 ┆ ww.sec.go ┆ d04c-511c ┆ rwin-Will ┆   ┆ WILLIAMS  ┆ d04c-511c ┆           ┆          │
│ 0         ┆ v/Archive ┆ -9a7d-b83 ┆ iams Foun ┆   ┆ CO        ┆ -9a7d-b83 ┆           ┆          │
│           ┆ s/edgar/d ┆ 4fba10378 ┆ dation is ┆   ┆           ┆ 4fba10378 ┆           ┆          │
│           ┆ ata/89800 ┆ -sub-2    ┆ a 501(c)  ┆   ┆           ┆           ┆           ┆          │
│           ┆ /00000898 ┆           ┆ organizat ┆   ┆           ┆           ┆           ┆          │
│           ┆ 002500003 ┆           ┆ ion and   ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0/shw-123 ┆           ┆ is not    ┆   ┆           ┆           ┆           ┆          │
│           ┆ 12024xex2 ┆           ┆ included  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 11.htm    ┆           ┆ within    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ the conso ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ lidated   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ financial ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ statement ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ s of The  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Sherwin   ┆   ┆           ┆           ┆           ┆          │
│ `00016282 ┆ https://w ┆ 18015b3d- ┆ Delek     ┆ … ┆ Aon plc   ┆ 9dfbce61- ┆ null      ┆ 2003     │
│ 802500609 ┆ ww.sec.go ┆ 9cb8-540c ┆ Motors    ┆   ┆           ┆ e3c6-5b84 ┆           ┆          │
│ 3         ┆ v/Archive ┆ -acbf-c8c ┆ Insurance ┆   ┆           ┆ -950b-fe9 ┆           ┆          │
│           ┆ s/edgar/d ┆ af1fcf930 ┆ Agency    ┆   ┆           ┆ 6ee044019 ┆           ┆          │
│           ┆ ata/31529 ┆           ┆ Ltd.      ┆   ┆           ┆           ┆           ┆          │
│           ┆ 3/0001628 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 280250060 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 93/exhibi ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ t2112024. ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ htm       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ `00016282 ┆ https://w ┆ 2ebd1f27- ┆ I. Beck   ┆ … ┆ Aon plc   ┆ 9dfbce61- ┆ null      ┆ 1994     │
│ 802500609 ┆ ww.sec.go ┆ 7dad-506d ┆ Insurance ┆   ┆           ┆ e3c6-5b84 ┆           ┆          │
│ 3         ┆ v/Archive ┆ -82b9-799 ┆ Agency    ┆   ┆           ┆ -950b-fe9 ┆           ┆          │
│           ┆ s/edgar/d ┆ 63cf1506f ┆ Ltd.      ┆   ┆           ┆ 6ee044019 ┆           ┆          │
│           ┆ ata/31529 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 3/0001628 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 280250060 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 93/exhibi ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ t2112024. ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ htm       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ `00000024 ┆ https://w ┆ 977c9b79- ┆ Auviz     ┆ … ┆ ADVANCED  ┆ 977c9b79- ┆ null      ┆ 1        │
│ 882500001 ┆ ww.sec.go ┆ a2e5-5281 ┆ Systems   ┆   ┆ MICRO     ┆ a2e5-5281 ┆           ┆          │
│ 2         ┆ v/Archive ┆ -b5f8-788 ┆ Inc       ┆   ┆ DEVICES   ┆ -b5f8-788 ┆           ┆          │
│           ┆ s/edgar/d ┆ 2adce84d8 ┆           ┆   ┆ INC       ┆ 2adce84d8 ┆           ┆          │
│           ┆ ata/2488/ ┆ -sub-5    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 000000248 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 825000012 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ /ex21-10k ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ fy2412_28 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ .htm      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ `00000024 ┆ https://w ┆ 977c9b79- ┆ Xilinx    ┆ … ┆ ADVANCED  ┆ 977c9b79- ┆ null      ┆ 1        │
│ 882500001 ┆ ww.sec.go ┆ a2e5-5281 ┆ Developme ┆   ┆ MICRO     ┆ a2e5-5281 ┆           ┆          │
│ 2         ┆ v/Archive ┆ -b5f8-788 ┆ nt Corpor ┆   ┆ DEVICES   ┆ -b5f8-788 ┆           ┆          │
│           ┆ s/edgar/d ┆ 2adce84d8 ┆ ation     ┆   ┆ INC       ┆ 2adce84d8 ┆           ┆          │
│           ┆ ata/2488/ ┆ -sub-6    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 000000248 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 825000012 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ /ex21-10k ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ fy2412_28 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ .htm      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ `00000024 ┆ https://w ┆ 977c9b79- ┆ Level 5   ┆ … ┆ ADVANCED  ┆ 977c9b79- ┆ null      ┆ 2        │
│ 882500001 ┆ ww.sec.go ┆ a2e5-5281 ┆ Networks  ┆   ┆ MICRO     ┆ a2e5-5281 ┆           ┆          │
│ 2         ┆ v/Archive ┆ -b5f8-788 ┆           ┆   ┆ DEVICES   ┆ -b5f8-788 ┆           ┆          │
│           ┆ s/edgar/d ┆ 2adce84d8 ┆           ┆   ┆ INC       ┆ 2adce84d8 ┆           ┆          │
│           ┆ ata/2488/ ┆ -sub-16   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 000000248 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 825000012 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ /ex21-10k ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ fy2412_28 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ .htm      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ `00000024 ┆ https://w ┆ 977c9b79- ┆ Midgard   ┆ … ┆ ADVANCED  ┆ 977c9b79- ┆ null      ┆ 1        │
│ 882500001 ┆ ww.sec.go ┆ a2e5-5281 ┆ Acquisiti ┆   ┆ MICRO     ┆ a2e5-5281 ┆           ┆          │
│ 2         ┆ v/Archive ┆ -b5f8-788 ┆ on LLC    ┆   ┆ DEVICES   ┆ -b5f8-788 ┆           ┆          │
│           ┆ s/edgar/d ┆ 2adce84d8 ┆           ┆   ┆ INC       ┆ 2adce84d8 ┆           ┆          │
│           ┆ ata/2488/ ┆ -sub-17   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 000000248 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 825000012 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ /ex21-10k ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ fy2412_28 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ .htm      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ `00000024 ┆ https://w ┆ 977c9b79- ┆ Mipsology ┆ … ┆ ADVANCED  ┆ 977c9b79- ┆ null      ┆ 26       │
│ 882500001 ┆ ww.sec.go ┆ a2e5-5281 ┆           ┆   ┆ MICRO     ┆ a2e5-5281 ┆           ┆          │
│ 2         ┆ v/Archive ┆ -b5f8-788 ┆           ┆   ┆ DEVICES   ┆ -b5f8-788 ┆           ┆          │
│           ┆ s/edgar/d ┆ 2adce84d8 ┆           ┆   ┆ INC       ┆ 2adce84d8 ┆           ┆          │
│           ┆ ata/2488/ ┆ -sub-18   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 000000248 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 825000012 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ /ex21-10k ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ fy2412_28 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ .htm      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ `00000024 ┆ https://w ┆ 977c9b79- ┆ NGCodec   ┆ … ┆ ADVANCED  ┆ 977c9b79- ┆ null      ┆ 1        │
│ 882500001 ┆ ww.sec.go ┆ a2e5-5281 ┆ Inc.      ┆   ┆ MICRO     ┆ a2e5-5281 ┆           ┆          │
│ 2         ┆ v/Archive ┆ -b5f8-788 ┆           ┆   ┆ DEVICES   ┆ -b5f8-788 ┆           ┆          │
│           ┆ s/edgar/d ┆ 2adce84d8 ┆           ┆   ┆ INC       ┆ 2adce84d8 ┆           ┆          │
│           ┆ ata/2488/ ┆ -sub-20   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 000000248 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 825000012 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ /ex21-10k ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ fy2412_28 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ .htm      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ `00000024 ┆ https://w ┆ 977c9b79- ┆ Silexica  ┆ … ┆ ADVANCED  ┆ 977c9b79- ┆ null      ┆ 1        │
│ 882500001 ┆ ww.sec.go ┆ a2e5-5281 ┆           ┆   ┆ MICRO     ┆ a2e5-5281 ┆           ┆          │
│ 2         ┆ v/Archive ┆ -b5f8-788 ┆           ┆   ┆ DEVICES   ┆ -b5f8-788 ┆           ┆          │
│           ┆ s/edgar/d ┆ 2adce84d8 ┆           ┆   ┆ INC       ┆ 2adce84d8 ┆           ┆          │
│           ┆ ata/2488/ ┆ -sub-24   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 000000248 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 825000012 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ /ex21-10k ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ fy2412_28 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ .htm      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ `00000024 ┆ https://w ┆ 977c9b79- ┆ Solarflar ┆ … ┆ ADVANCED  ┆ 977c9b79- ┆ null      ┆ 1        │
│ 882500001 ┆ ww.sec.go ┆ a2e5-5281 ┆ e Communi ┆   ┆ MICRO     ┆ a2e5-5281 ┆           ┆          │
│ 2         ┆ v/Archive ┆ -b5f8-788 ┆ cations   ┆   ┆ DEVICES   ┆ -b5f8-788 ┆           ┆          │
│           ┆ s/edgar/d ┆ 2adce84d8 ┆           ┆   ┆ INC       ┆ 2adce84d8 ┆           ┆          │
│           ┆ ata/2488/ ┆ -sub-25   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 000000248 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 825000012 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ /ex21-10k ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ fy2412_28 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ .htm      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ `00000024 ┆ https://w ┆ 977c9b79- ┆ Xilinx    ┆ … ┆ ADVANCED  ┆ 977c9b79- ┆ null      ┆ 1        │
│ 882500001 ┆ ww.sec.go ┆ a2e5-5281 ┆ Holding   ┆   ┆ MICRO     ┆ a2e5-5281 ┆           ┆          │
│ 2         ┆ v/Archive ┆ -b5f8-788 ┆ LLC       ┆   ┆ DEVICES   ┆ -b5f8-788 ┆           ┆          │
│           ┆ s/edgar/d ┆ 2adce84d8 ┆           ┆   ┆ INC       ┆ 2adce84d8 ┆           ┆          │
│           ┆ ata/2488/ ┆ -sub-26   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 000000248 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 825000012 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ /ex21-10k ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ fy2412_28 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ .htm      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ `00000024 ┆ https://w ┆ 977c9b79- ┆ Xilinx    ┆ … ┆ ADVANCED  ┆ 977c9b79- ┆ null      ┆ 1        │
│ 882500001 ┆ ww.sec.go ┆ a2e5-5281 ┆ Armenia   ┆   ┆ MICRO     ┆ a2e5-5281 ┆           ┆          │
│ 2         ┆ v/Archive ┆ -b5f8-788 ┆ LLC       ┆   ┆ DEVICES   ┆ -b5f8-788 ┆           ┆          │
│           ┆ s/edgar/d ┆ 2adce84d8 ┆           ┆   ┆ INC       ┆ 2adce84d8 ┆           ┆          │
│           ┆ ata/2488/ ┆ -sub-27   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 000000248 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 825000012 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ /ex21-10k ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ fy2412_28 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ .htm      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ `00000024 ┆ https://w ┆ 977c9b79- ┆ ATI Inter ┆ … ┆ ADVANCED  ┆ 977c9b79- ┆ null      ┆ 3        │
│ 882500001 ┆ ww.sec.go ┆ a2e5-5281 ┆ national  ┆   ┆ MICRO     ┆ a2e5-5281 ┆           ┆          │
│ 2         ┆ v/Archive ┆ -b5f8-788 ┆ SRL       ┆   ┆ DEVICES   ┆ -b5f8-788 ┆           ┆          │
│           ┆ s/edgar/d ┆ 2adce84d8 ┆           ┆   ┆ INC       ┆ 2adce84d8 ┆           ┆          │
│           ┆ ata/2488/ ┆ -sub-28   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 000000248 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 825000012 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ /ex21-10k ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ fy2412_28 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ .htm      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ `00000024 ┆ https://w ┆ 977c9b79- ┆ ATI Techn ┆ … ┆ ADVANCED  ┆ 977c9b79- ┆ null      ┆ 3        │
│ 882500001 ┆ ww.sec.go ┆ a2e5-5281 ┆ ologies   ┆   ┆ MICRO     ┆ a2e5-5281 ┆           ┆          │
│ 2         ┆ v/Archive ┆ -b5f8-788 ┆ (Bermuda) ┆   ┆ DEVICES   ┆ -b5f8-788 ┆           ┆          │
│           ┆ s/edgar/d ┆ 2adce84d8 ┆ Limited   ┆   ┆ INC       ┆ 2adce84d8 ┆           ┆          │
│           ┆ ata/2488/ ┆ -sub-29   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 000000248 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 825000012 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │

In [20]:
# Unique footnote values per accession
footnotes_by_accession = df.filter(
    pl.col("Footnotes").is_not_null() & (pl.col("Footnotes").str.strip_chars() != "")
).group_by("Accession").agg(
    pl.col("Footnotes").unique().alias("UniqueFootnotes")
)

print(f"Accessions with footnotes: {len(footnotes_by_accession)}")
print(f"\nAccession: Footnotes")
for row in footnotes_by_accession.iter_rows():
    print(f"{row[0]}: {row[1]}")

Accessions with footnotes: 37

Accession: Footnotes
`000007747625000007: ['2018']
`000109921925000044: ['2002']
`000155837025003413: ['1', '2, 15', '3', '4', '5', '6', '7', '9', '10', '12', '13, 15', '14', '14, 15', '16', '17', '18', '19', '21']
`000007736025000006: ['1', '2', '3', '4', '5', '6']
`000089905125000015: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19']
`000162828025037656: ['1']
`000000497725000047: ['1', '2', '3', '4', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17']
`000155837025001222: ['10']
`000155837025001263: ['1']
`000112336025000011: ['2', '1']
`000105350725000025: ['2', '3', '5', '1', '6', '4']
`000095017025024750: ['2', '3', '4']
`000031920125000024: ['1992', '1987', '2002']
`000139718725000013: ['1']
`000119312525034579: ['1', '2']
`000093570325000015: ['1']
`000076447825000007: ['1', '2', '3', '4', '5', '6', '7']
`000171126925000004: ['2']
`000138119725000036: ['1', '2', '3']
`000000248825000012: ['1', '2', '26', '3', '7', '8', '9', '10', '11', '12', '13', '28', '14', '15', '25', '24', '16', '17', '18', '29', '27', '5', '22', '21']
`000003408825000010: ['4, 5', '5', '2']
`000162828025005715: ['43', '23', '1']
`000087721225000027: ['2007']
`000151029525000012: ['1']
`000132440425000006: ['3', '2']
`000004054525000015: ['1']
`000006270925000015: ['2005', '1999']
`000085973725000072: ['21']
`000162828025006093: ['2003', '1994']
`000010416925000021: ['1']
`000128176125000010: ['4', '7', '8', '10', '6', '2', '5', '12', '1', '3']
`000008980025000030: ['3']
`000087532025000053: ['9', '4', '1', '5', '6', '2', '7', '8', '3']
`000199681025000011: ['1']
`000005125325000013: ['1', '2', '3', '4', '5', '6', '7', '8']
`000001154425000005: ['2', '3', '4']
`000162828025007110: ['2']

In [21]:
# Unique footnote values - extract all individual numbers with their accessions
import re

footnotes_with_accession = df.filter(
    pl.col("Footnotes").is_not_null() & (pl.col("Footnotes").str.strip_chars() != "")
).select(["Accession", "Footnotes"]).unique()

# Build a dict: number -> list of accessions
number_to_accessions = {}
for row in footnotes_with_accession.iter_rows():
    accession, footnote = row
    nums = re.findall(r'\d+', footnote)
    for n in nums:
        num = int(n)
        if num not in number_to_accessions:
            number_to_accessions[num] = set()
        number_to_accessions[num].add(accession)

# Sort by number descending and print
sorted_items = sorted(number_to_accessions.items(), key=lambda x: x[0], reverse=True)

print(f"Total unique footnote numbers: {len(sorted_items)}")
print(f"\nFootnoteNumber: Accessions")
for num, accs in sorted_items:
    print(f"{num}: {list(accs)}")

Total unique footnote numbers: 38

FootnoteNumber: Accessions
2018: ['`000007747625000007']
2007: ['`000087721225000027']
2005: ['`000006270925000015']
2003: ['`000162828025006093']
2002: ['`000109921925000044', '`000031920125000024']
1999: ['`000006270925000015']
1994: ['`000162828025006093']
1992: ['`000031920125000024']
1987: ['`000031920125000024']
43: ['`000162828025005715']
29: ['`000000248825000012']
28: ['`000000248825000012']
27: ['`000000248825000012']
26: ['`000000248825000012']
25: ['`000000248825000012']
24: ['`000000248825000012']
23: ['`000162828025005715']
22: ['`000000248825000012']
21: ['`000085973725000072', '`000155837025003413', '`000000248825000012']
19: ['`000155837025003413', '`000089905125000015']
18: ['`000000248825000012', '`000155837025003413', '`000089905125000015']
17: ['`000000497725000047', '`000000248825000012', '`000155837025003413', '`000089905125000015']
16: ['`000000497725000047', '`000155837025003413', '`000089905125000015', '`000000248825000012']
15: ['`000000497725000047', '`000000248825000012', '`000155837025003413', '`000089905125000015']
14: ['`000000497725000047', '`000000248825000012', '`000155837025003413', '`000089905125000015']
13: ['`000000497725000047', '`000155837025003413', '`000089905125000015', '`000000248825000012']
12: ['`000000497725000047', '`000000248825000012', '`000089905125000015', '`000128176125000010', '`000155837025003413']
11: ['`000089905125000015', '`000000248825000012', '`000000497725000047']
10: ['`000000248825000012', '`000000497725000047', '`000089905125000015', '`000128176125000010', '`000155837025003413', '`000155837025001222']
9: ['`000000497725000047', '`000000248825000012', '`000087532025000053', '`000089905125000015', '`000155837025003413']
8: ['`000000497725000047', '`000000248825000012', '`000005125325000013', '`000087532025000053', '`000089905125000015', '`000128176125000010']
7: ['`000000497725000047', '`000076447825000007', '`000000248825000012', '`000005125325000013', '`000087532025000053', '`000089905125000015', '`000128176125000010', '`000155837025003413']
6: ['`000000497725000047', '`000076447825000007', '`000005125325000013', '`000087532025000053', '`000105350725000025', '`000089905125000015', '`000007736025000006', '`000128176125000010', '`000155837025003413']
5: ['`000000248825000012', '`000076447825000007', '`000005125325000013', '`000087532025000053', '`000003408825000010', '`000089905125000015', '`000105350725000025', '`000007736025000006', '`000128176125000010', '`000155837025003413']
4: ['`000000497725000047', '`000001154425000005', '`000076447825000007', '`000005125325000013', '`000095017025024750', '`000087532025000053', '`000003408825000010', '`000105350725000025', '`000089905125000015', '`000007736025000006', '`000128176125000010', '`000155837025003413']
3: ['`000000497725000047', '`000001154425000005', '`000000248825000012', '`000076447825000007', '`000138119725000036', '`000005125325000013', '`000008980025000030', '`000087532025000053', '`000095017025024750', '`000105350725000025', '`000089905125000015', '`000007736025000006', '`000128176125000010', '`000155837025003413', '`000132440425000006']
2: ['`000138119725000036', '`000119312525034579', '`000095017025024750', '`000087532025000053', '`000112336025000011', '`000076447825000007', '`000162828025007110', '`000171126925000004', '`000000497725000047', '`000003408825000010', '`000105350725000025', '`000007736025000006', '`000128176125000010', '`000155837025003413', '`000132440425000006', '`000000248825000012', '`000001154425000005', '`000005125325000013', '`000089905125000015']
1: ['`000138119725000036', '`000119312525034579', '`000087532025000053', '`000199681025000011', '`000112336025000011', '`000076447825000007', '`000093570325000015', '`000151029525000012', '`000000497725000047', '`000105350725000025', '`000007736025000006', '`000155837025001263', '`000128176125000010', '`000162828025005715', '`000155837025003413', '`000000248825000012', '`000004054525000015', '`000005125325000013', '`000162828025037656', '`000139718725000013', '`000089905125000015', '`000010416925000021']