# Subsidiary Data Analysis
Analyze parsed subsidiary data from SEC filings

## 0. Setup

In [1]:
import polars as pl
from pathlib import Path

# Load CSV
csv_path = Path("../../../../subsidiaries_SUCCESS.csv")
df = pl.read_csv(csv_path, schema_overrides={"Ownership": pl.Float64})

print(f"Total rows: {len(df):,}")
print(f"Columns: {df.columns}")
df.head()

Total rows: 180,570
Columns: ['Accession', 'URL', 'SubsidiaryId', 'Subsidiary', 'Jurisdiction', 'NestingLevel', 'ParentName', 'ParentId', 'Ownership', 'Footnotes']

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Accession ┆ URL       ┆ Subsidiar ┆ Subsidiar ┆ … ┆ ParentNam ┆ ParentId  ┆ Ownership ┆ Footnote │
│ ---       ┆ ---       ┆ yId       ┆ y         ┆   ┆ e         ┆ ---       ┆ ---       ┆ s        │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ f64       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ `00009501 ┆ https://w ┆ b91a4c12- ┆ Medallion ┆ … ┆ null      ┆ 6bd69361- ┆ 100.0     ┆          │
│ 702503869 ┆ ww.sec.go ┆ 0b65-530a ┆ Funding   ┆   ┆           ┆ 5068-5121 ┆           ┆          │
│ 3         ┆ v/Archive ┆ -bb38-31a ┆ LLC       ┆   ┆           ┆ -9d53-9dd ┆           ┆          │
│           ┆ s/e…      ┆ 138…      ┆           ┆   ┆           ┆ 804…      ┆           ┆          │
│ `00009501 ┆ https://w ┆ c812f033- ┆ Medallion ┆ … ┆ null      ┆ 6bd69361- ┆ 100.0     ┆          │
│ 702503869 ┆ ww.sec.go ┆ 3f07-594d ┆ Capital,  ┆   ┆           ┆ 5068-5121 ┆           ┆          │
│ 3         ┆ v/Archive ┆ -945e-e01 ┆ Inc.      ┆   ┆           ┆ -9d53-9dd ┆           ┆          │
│           ┆ s/e…      ┆ 923…      ┆           ┆   ┆           ┆ 804…      ┆           ┆          │
│ `00009501 ┆ https://w ┆ 6c9072d2- ┆ Freshstar ┆ … ┆ null      ┆ 6bd69361- ┆ 100.0     ┆          │
│ 702503869 ┆ ww.sec.go ┆ 14b2-52a5 ┆ t Venture ┆   ┆           ┆ 5068-5121 ┆           ┆          │
│ 3         ┆ v/Archive ┆ -8d54-631 ┆ Capital   ┆   ┆           ┆ -9d53-9dd ┆           ┆          │
│           ┆ s/e…      ┆ bf4…      ┆ Cor…      ┆   ┆           ┆ 804…      ┆           ┆          │
│ `00009501 ┆ https://w ┆ 23a12c5a- ┆ Medallion ┆ … ┆ null      ┆ 6bd69361- ┆ 100.0     ┆          │
│ 702503869 ┆ ww.sec.go ┆ d217-5efe ┆ Bank      ┆   ┆           ┆ 5068-5121 ┆           ┆          │
│ 3         ┆ v/Archive ┆ -9cb6-0d7 ┆           ┆   ┆           ┆ -9d53-9dd ┆           ┆          │
│           ┆ s/e…      ┆ 4cf…      ┆           ┆   ┆           ┆ 804…      ┆           ┆          │
│ `00010002 ┆ https://w ┆ a7a40ef8- ┆ ACE       ┆ … ┆ null      ┆ 0644a2d7- ┆ 100.0     ┆          │
│ 282500001 ┆ ww.sec.go ┆ 7c84-5a0e ┆ Surgical  ┆   ┆           ┆ c768-5a0d ┆           ┆          │
│ 4         ┆ v/Archive ┆ -8e70-ca3 ┆ Supply    ┆   ┆           ┆ -aca8-834 ┆           ┆          │
│           ┆ s/e…      ┆ aef…      ┆ Co., Inc. ┆   ┆           ┆ 06d…      ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [2]:
# Basic stats
df.describe()

shape: (9, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ Accession ┆ URL       ┆ Subsidiar ┆ … ┆ ParentNam ┆ ParentId  ┆ Ownership ┆ Footnote │
│ ---       ┆ ---       ┆ ---       ┆ yId       ┆   ┆ e         ┆ ---       ┆ ---       ┆ s        │
│ str       ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ str       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 180570    ┆ 180570    ┆ 180570    ┆ … ┆ 3816      ┆ 180570    ┆ 179945.0  ┆ 180570   │
│ null_coun ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 176754    ┆ 0         ┆ 625.0     ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 99.48815  ┆ null     │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 5.49318   ┆ null     │
│ min       ┆ `00000024 ┆ https://w ┆ 00005b18- ┆ … ┆ 0896800   ┆ 002b5809- ┆ 0.0       ┆          │
│           ┆ 882500001 ┆ ww.sec.go ┆ bbee-5662 ┆   ┆ B.C. Ltd. ┆ de06-5c7c ┆           ┆          │
│           ┆ 2         ┆ v/Archive ┆ -b85d-d58 ┆   ┆           ┆ -a24e-824 ┆           ┆          │
│           ┆           ┆ s/e…      ┆ 635…      ┆   ┆           ┆ 76e…      ┆           ┆          │
│ 25%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 100.0     ┆ null     │
│ 50%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 100.0     ┆ null     │
│ 75%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 100.0     ┆ null     │
│ max       ┆ `00020770 ┆ https://w ┆ fffff536- ┆ … ┆ ◦Kanawha  ┆ ffef8561- ┆ 100.0     ┆ 99       │
│           ┆ 962500010 ┆ ww.sec.go ┆ ec32-5f41 ┆   ┆ River     ┆ 669b-5240 ┆           ┆          │
│           ┆ 7         ┆ v/Archive ┆ -8f42-484 ┆   ┆ Terminals ┆ -b1f5-b2a ┆           ┆          │
│           ┆           ┆ s/e…      ┆ 85d…      ┆   ┆ LLC       ┆ c5d…      ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
# Query rows for a specific accession
accession_to_find = "`000162828025008991"
df.filter(pl.col("Accession") == accession_to_find).head(10)

shape: (5, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Accession ┆ URL       ┆ Subsidiar ┆ Subsidiar ┆ … ┆ ParentNam ┆ ParentId  ┆ Ownership ┆ Footnote │
│ ---       ┆ ---       ┆ yId       ┆ y         ┆   ┆ e         ┆ ---       ┆ ---       ┆ s        │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ f64       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ `00016282 ┆ https://w ┆ 96364b78- ┆ Provident ┆ … ┆ null      ┆ 6211cfe6- ┆ 100.0     ┆          │
│ 802500899 ┆ ww.sec.go ┆ ea28-5a0f ┆ Financial ┆   ┆           ┆ 9e02-5941 ┆           ┆          │
│ 1         ┆ v/Archive ┆ -8b81-299 ┆ Services, ┆   ┆           ┆ -a2bb-1c8 ┆           ┆          │
│           ┆ s/e…      ┆ a97…      ┆ …         ┆   ┆           ┆ 107…      ┆           ┆          │
│ `00016282 ┆ https://w ┆ 63913fc1- ┆ Sussex    ┆ … ┆ null      ┆ 6211cfe6- ┆ 100.0     ┆          │
│ 802500899 ┆ ww.sec.go ┆ 2756-5fcc ┆ Capital   ┆   ┆           ┆ 9e02-5941 ┆           ┆          │
│ 1         ┆ v/Archive ┆ -a0a6-5f8 ┆ Trust II  ┆   ┆           ┆ -a2bb-1c8 ┆           ┆          │
│           ┆ s/e…      ┆ 93f…      ┆           ┆   ┆           ┆ 107…      ┆           ┆          │
│ `00016282 ┆ https://w ┆ be8d5cfd- ┆ 1st Const ┆ … ┆ null      ┆ 6211cfe6- ┆ 100.0     ┆          │
│ 802500899 ┆ ww.sec.go ┆ 0587-52ce ┆ itution   ┆   ┆           ┆ 9e02-5941 ┆           ┆          │
│ 1         ┆ v/Archive ┆ -9957-eae ┆ Capital   ┆   ┆           ┆ -a2bb-1c8 ┆           ┆          │
│           ┆ s/e…      ┆ e24…      ┆ Trust…    ┆   ┆           ┆ 107…      ┆           ┆          │
│ `00016282 ┆ https://w ┆ 1f14f247- ┆ Lakeland  ┆ … ┆ null      ┆ 6211cfe6- ┆ 100.0     ┆          │
│ 802500899 ┆ ww.sec.go ┆ ec43-5996 ┆ Bancorp   ┆   ┆           ┆ 9e02-5941 ┆           ┆          │
│ 1         ┆ v/Archive ┆ -8baa-d1a ┆ Capital   ┆   ┆           ┆ -a2bb-1c8 ┆           ┆          │
│           ┆ s/e…      ┆ 8f6…      ┆ Trust…    ┆   ┆           ┆ 107…      ┆           ┆          │
│ `00016282 ┆ https://w ┆ f595ab0b- ┆ Lakeland  ┆ … ┆ null      ┆ 6211cfe6- ┆ 100.0     ┆          │
│ 802500899 ┆ ww.sec.go ┆ 064b-556b ┆ Bancorp   ┆   ┆           ┆ 9e02-5941 ┆           ┆          │
│ 1         ┆ v/Archive ┆ -820c-a7d ┆ Capital   ┆   ┆           ┆ -a2bb-1c8 ┆           ┆          │
│           ┆ s/e…      ┆ 03f…      ┆ Trust…    ┆   ┆           ┆ 107…      ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
# Find rows with empty or null jurisdiction
empty_jurisdiction = df.filter(
    pl.col("Jurisdiction").is_null() | (pl.col("Jurisdiction").str.strip_chars() == "")
)

unique_accessions = empty_jurisdiction.select("Accession").unique()
print(f"Rows with empty jurisdiction: {len(empty_jurisdiction):,}")

print(f"\nUnique accession list({len(unique_accessions)}): ")
print(unique_accessions.to_series().to_list())
empty_jurisdiction.head(10)

Rows with empty jurisdiction: 0

Unique accession list(0):
[]

shape: (0, 10)
┌───────────┬─────┬──────────────┬────────────┬───┬────────────┬──────────┬───────────┬───────────┐
│ Accession ┆ URL ┆ SubsidiaryId ┆ Subsidiary ┆ … ┆ ParentName ┆ ParentId ┆ Ownership ┆ Footnotes │
│ ---       ┆ --- ┆ ---          ┆ ---        ┆   ┆ ---        ┆ ---      ┆ ---       ┆ ---       │
│ str       ┆ str ┆ str          ┆ str        ┆   ┆ str        ┆ str      ┆ f64       ┆ str       │
╞═══════════╪═════╪══════════════╪════════════╪═══╪════════════╪══════════╪═══════════╪═══════════╡
└───────────┴─────┴──────────────┴────────────┴───┴────────────┴──────────┴───────────┴───────────┘

## 1. Nested Subsidiaries (NestingLevel >= 1)

In [5]:
# Find nested subsidiaries
nested = df.filter(pl.col("NestingLevel") >= 1)

nested_accessions = nested.select("Accession").unique()
print(f"Nested subsidiaries (level >= 1): {len(nested):,}")

print(f"Unique accession list({len(nested_accessions)}):")
print(nested_accessions.to_series().to_list())
# nested.head(20)


# Filter by specific accession
pl.Config.set_tbl_rows(-1) 
target_accession = '`000007889025000059'
df.filter(pl.col("Accession") == target_accession)

Nested subsidiaries (level >= 1): 6,120
Unique accession list(188):
['`000103130825000002', '`000162828025015673', '`000159696125000024', '`000162828025053871', '`000092480525000012', '`000185224425000007', '`000155943225000035', '`000162828025008121', '`000095017025047891', '`000129281425001352', '`000007169125000047', '`000116486325000009', '`000169913625000014', '`000121390025018782', '`000132611025000033', '`000089542125000304', '`000119312525319187', '`000161755325000011', '`000162828025020368', '`000162828025054103', '`000000497725000047', '`000162828025008730', '`000000620125000010', '`000007889025000059', '`000162828025009448', '`000121390025035542', '`000093905725000159', '`000163720725000016', '`000009212225000018', '`000088461425000053', '`000187901625000003', '`000143774925010228', '`000154565425000005', '`000192956125000044', '`000166028025000034', '`000162828025011831', '`000162828025009503', '`000131415225000031', '`000160548425000013', '`000160402825000012', '`000081158925000008', '`000095017025046096', '`000144530525000034', '`000133152025000076', '`000186074225000004', '`000162828025010947', '`000021622825000014', '`000007528825000033', '`000005114325000015', '`000086073125000007', '`000146737325000217', '`000186919825000009', '`000020040625000038', '`000100307825000123', '`000006638225000069', '`000141210025000011', '`000121390025032203', '`000077149725000031', '`000109507325000015', '`000188953925000014', '`000001961725000270', '`000102312825000026', '`000182831625000017', '`000006674025000006', '`000095017025022244', '`000095017025045214', '`000121390025030345', '`000121390025032266', '`000076406525000058', '`000010781525000103', '`000070895525000012', '`000162828025005392', '`000082554225000022', '`000008553525000012', '`000000496225000016', '`000109634325000027', '`000093041325000900', '`000155837025004669', '`000121390025017221', '`000105044125000051', '`000077240625000014', '`000163279025000091', '`000008631225000012', '`000006675625000013', '`000095017025023983', '`000006299625000004', '`000095017025078451', '`000162828025014318', '`000162828025006557', '`000133398625000011', '`000131916125000034', '`000169051125000011', '`000089615925000004', '`000109269925000011', '`000162828025006184', '`000130696525000007', '`000006375425000005', '`000162828025008728', '`000197323925000016', '`000121390025027319', '`000008943925000010', '`000003877725000238', '`000111316925000007', '`000121390025044868', '`000196891525000006', '`000095017025026866', '`000173399825000020', '`000104204625000011', '`000162828025008656', '`000010051725000046', '`000105572625000012', '`000181428725000006', '`000071742325000006', '`000162828025014348', '`000021546625000009', '`000162828025020808', '`000141626525000006', '`000181001925000043', '`000155485525000232', '`000095017025048724', '`000107997325000827', '`000143757825000007', '`000162828025018102', '`000162828025004633', '`000149983225000040', '`000133692025000006', '`000143774925029909', '`000003552725000079', '`000145180925000034', '`000000428125000011', '`000170904825000024', '`000100683725000021', '`000170569625000033', '`000007426025000042', '`000194136525000016', '`000106770125000008', '`000151470525000004', '`000180373725000049', '`000169903925000015', '`000139898725000020', '`000144889325000009', '`000160062625000017', '`000165347725000015', '`000079634325000004', '`000162828025012095', '`000110813425000003', '`000100291025000055', '`000148939325000008', '`000007823925000018', '`000004661925000082', '`000116600325000017', '`000119983525000414', '`000010919825000010', '`000170160525000035', '`000170803525000070', '`000085120525000012', '`000095017025038692', '`000095017025029095', '`000138627825000009', '`000162828025007721', '`000002617225000007', '`000001834925000049', '`000079461925000061', '`000021734625000017', '`000095017025029184', '`000181984825000196', '`000008066125000007', '`000123024525000038', '`000085785525000057', '`000180117025000052', '`000136686825000033', '`000084048925000032', '`000170472025000015', '`000095017025038326', '`000095017025029973', '`000157112325000022', '`000165785325000015', '`000181997425000010', '`000162828025004859', '`000071664325000031', '`000109355725000036', '`000162828025056742', '`000088933125000039', '`000146762325000011', '`000095017025030795', '`000003696625000024', '`000095017025023736', '`000006598425000012']

shape: (268, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Accession ┆ URL       ┆ Subsidiar ┆ Subsidiar ┆ … ┆ ParentNam ┆ ParentId  ┆ Ownership ┆ Footnote │
│ ---       ┆ ---       ┆ yId       ┆ y         ┆   ┆ e         ┆ ---       ┆ ---       ┆ s        │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ f64       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ `00000788 ┆ https://w ┆ ead19cab- ┆ The       ┆ … ┆ null      ┆ 6efe832d- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 71d0-5258 ┆ Pittston  ┆   ┆           ┆ 6b6b-5802 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -9aaf-b39 ┆ Company   ┆   ┆           ┆ -a8fb-92c ┆           ┆          │
│           ┆ s/e…      ┆ 46c…      ┆           ┆   ┆           ┆ aa2…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ a39d0fa8- ┆ Glen      ┆ … ┆ null      ┆ 6efe832d- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ f1e5-5d5f ┆ Allen Dev ┆   ┆           ┆ 6b6b-5802 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -82ac-10d ┆ elopment, ┆   ┆           ┆ -a8fb-92c ┆           ┆          │
│           ┆ s/e…      ┆ f52…      ┆ Inc.      ┆   ┆           ┆ aa2…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ cb1c82c2- ┆ Liberty   ┆ … ┆ Glen      ┆ a39d0fa8- ┆ 32.5      ┆          │
│ 902500005 ┆ ww.sec.go ┆ 1818-51f3 ┆ National  ┆   ┆ Allen Dev ┆ f1e5-5d5f ┆           ┆          │
│ 9         ┆ v/Archive ┆ -bbfa-244 ┆ Developme ┆   ┆ elopment, ┆ -82ac-10d ┆           ┆          │
│           ┆ s/e…      ┆ 31a…      ┆ nt C…     ┆   ┆ Inc.      ┆ f52…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 745520ca- ┆ New       ┆ … ┆ Glen      ┆ a39d0fa8- ┆ 17.5      ┆          │
│ 902500005 ┆ ww.sec.go ┆ 2daf-5858 ┆ Liberty   ┆   ┆ Allen Dev ┆ f1e5-5d5f ┆           ┆          │
│ 9         ┆ v/Archive ┆ -b812-d14 ┆ Residenti ┆   ┆ elopment, ┆ -82ac-10d ┆           ┆          │
│           ┆ s/e…      ┆ 6d7…      ┆ al Urban  ┆   ┆ Inc.      ┆ f52…      ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ `00000788 ┆ https://w ┆ b13312e2- ┆ Pittston  ┆ … ┆ null      ┆ 6efe832d- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ bcfd-521b ┆ Services  ┆   ┆           ┆ 6b6b-5802 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -83f1-1ea ┆ Group     ┆   ┆           ┆ -a8fb-92c ┆           ┆          │
│           ┆ s/e…      ┆ bed…      ┆ Inc.      ┆   ┆           ┆ aa2…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ e8563236- ┆ Brink’s   ┆ … ┆ Pittston  ┆ b13312e2- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ f104-55b5 ┆ Holding   ┆   ┆ Services  ┆ bcfd-521b ┆           ┆          │
│ 9         ┆ v/Archive ┆ -a23a-686 ┆ Company   ┆   ┆ Group     ┆ -83f1-1ea ┆           ┆          │
│           ┆ s/e…      ┆ 22d…      ┆           ┆   ┆ Inc.      ┆ bed…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 83a69848- ┆ Brink’s   ┆ … ┆ Brink’s   ┆ e8563236- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 1ce7-5a7d ┆ Finance   ┆   ┆ Holding   ┆ f104-55b5 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -88ed-873 ┆ Holding   ┆   ┆ Company   ┆ -a23a-686 ┆           ┆          │
│           ┆ s/e…      ┆ 563…      ┆ Compan…   ┆   ┆           ┆ 22d…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 5716b250- ┆ Brink’s   ┆ … ┆ Brink’s   ┆ 83a69848- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ b1d1-5923 ┆ Capital   ┆   ┆ Finance   ┆ 1ce7-5a7d ┆           ┆          │
│ 9         ┆ v/Archive ┆ -a92c-015 ┆ Holding   ┆   ┆ Holding   ┆ -88ed-873 ┆           ┆          │
│           ┆ s/e…      ┆ d0c…      ┆ Compan…   ┆   ┆ Compan…   ┆ 563…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 6111f985- ┆ Brink’s   ┆ … ┆ Brink’s   ┆ 5716b250- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 879c-5333 ┆ Capital,  ┆   ┆ Capital   ┆ b1d1-5923 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -a2da-741 ┆ LLC       ┆   ┆ Holding   ┆ -a92c-015 ┆           ┆          │
│           ┆ s/e…      ┆ 3ce…      ┆           ┆   ┆ Compan…   ┆ d0c…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 49c16f0c- ┆ Brink’s   ┆ … ┆ Brink’s   ┆ 83a69848- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 5cc2-5850 ┆ Capital   ┆   ┆ Finance   ┆ 1ce7-5a7d ┆           ┆          │
│ 9         ┆ v/Archive ┆ -bb8e-4f2 ┆ Canada    ┆   ┆ Holding   ┆ -88ed-873 ┆           ┆          │
│           ┆ s/e…      ┆ 728…      ┆ Holding…  ┆   ┆ Compan…   ┆ 563…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ a791ab21- ┆ Brink’s   ┆ … ┆ Brink’s   ┆ 49c16f0c- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 0c4c-5a6c ┆ Capital   ┆   ┆ Capital   ┆ 5cc2-5850 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -8216-768 ┆ Canada    ┆   ┆ Canada    ┆ -bb8e-4f2 ┆           ┆          │
│           ┆ s/e…      ┆ e19…      ┆ Ltd       ┆   ┆ Holding…  ┆ 728…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ ae027b46- ┆ Brink’s   ┆ … ┆ Brink’s   ┆ 83a69848- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ e28a-5b2b ┆ Finance   ┆   ┆ Finance   ┆ 1ce7-5a7d ┆           ┆          │
│ 9         ┆ v/Archive ┆ -a909-924 ┆ Holding   ┆   ┆ Holding   ┆ -88ed-873 ┆           ┆          │
│           ┆ s/e…      ┆ a31…      ┆ Brasil…   ┆   ┆ Compan…   ┆ 563…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ d9214f73- ┆ Brink’s   ┆ … ┆ Brink’s   ┆ ae027b46- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 91ad-57da ┆ Pay Insti ┆   ┆ Finance   ┆ e28a-5b2b ┆           ┆          │
│ 9         ┆ v/Archive ┆ -830b-70a ┆ tuicao de ┆   ┆ Holding   ┆ -a909-924 ┆           ┆          │
│           ┆ s/e…      ┆ be0…      ┆ Pag…      ┆   ┆ Brasil…   ┆ a31…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 50e9123d- ┆ Brink’s,  ┆ … ┆ Brink’s   ┆ e8563236- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 6ad9-5c9a ┆ Incorpora ┆   ┆ Holding   ┆ f104-55b5 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -b00a-656 ┆ ted       ┆   ┆ Company   ┆ -a23a-686 ┆           ┆          │
│           ┆ s/e…      ┆ fd0…      ┆           ┆   ┆           ┆ 22d…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 162cd595- ┆ Brink’s   ┆ … ┆ Brink’s,  ┆ 50e9123d- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ e369-5bbf ┆ Delaware, ┆   ┆ Incorpora ┆ 6ad9-5c9a ┆           ┆          │
│ 9         ┆ v/Archive ┆ -a49c-c65 ┆ LLC       ┆   ┆ ted       ┆ -b00a-656 ┆           ┆          │
│           ┆ s/e…      ┆ 7c9…      ┆           ┆   ┆           ┆ fd0…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ ae45e88d- ┆ Brink’s   ┆ … ┆ Brink’s,  ┆ 50e9123d- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ adcb-550b ┆ AR LLC    ┆   ┆ Incorpora ┆ 6ad9-5c9a ┆           ┆          │
│ 9         ┆ v/Archive ┆ -b91a-e16 ┆           ┆   ┆ ted       ┆ -b00a-656 ┆           ┆          │
│           ┆ s/e…      ┆ 570…      ┆           ┆   ┆           ┆ fd0…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 1407e7cf- ┆ PAI       ┆ … ┆ Brink’s,  ┆ 50e9123d- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 66b6-50f4 ┆ Midco,    ┆   ┆ Incorpora ┆ 6ad9-5c9a ┆           ┆          │
│ 9         ┆ v/Archive ┆ -83e4-d04 ┆ Inc.      ┆   ┆ ted       ┆ -b00a-656 ┆           ┆          │
│           ┆ s/e…      ┆ 73e…      ┆           ┆   ┆           ┆ fd0…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 168eb2b7- ┆ Payment   ┆ … ┆ PAI       ┆ 1407e7cf- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 3022-5c3d ┆ Alliance  ┆   ┆ Midco,    ┆ 66b6-50f4 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -ab4b-7e8 ┆ Processin ┆   ┆ Inc.      ┆ -83e4-d04 ┆           ┆          │
│           ┆ s/e…      ┆ dc1…      ┆ g Co…     ┆   ┆           ┆ 73e…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ b3dc424d- ┆ Testlink  ┆ … ┆ Payment   ┆ 168eb2b7- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 6158-586c ┆ USA, Inc. ┆   ┆ Alliance  ┆ 3022-5c3d ┆           ┆          │
│ 9         ┆ v/Archive ┆ -9f86-d24 ┆           ┆   ┆ Processin ┆ -ab4b-7e8 ┆           ┆          │
│           ┆ s/e…      ┆ 68b…      ┆           ┆   ┆ g Co…     ┆ dc1…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 678d9a28- ┆ Payment   ┆ … ┆ Payment   ┆ 168eb2b7- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ b194-588f ┆ Alliance  ┆   ┆ Alliance  ┆ 3022-5c3d ┆           ┆          │
│ 9         ┆ v/Archive ┆ -86a0-484 ┆ Internati ┆   ┆ Processin ┆ -ab4b-7e8 ┆           ┆          │
│           ┆ s/e…      ┆ 8ba…      ┆ onal…     ┆   ┆ g Co…     ┆ dc1…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ af8d16e4- ┆ Vantage   ┆ … ┆ Payment   ┆ 678d9a28- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 0d0f-5915 ┆ Technical ┆   ┆ Alliance  ┆ b194-588f ┆           ┆          │
│ 9         ┆ v/Archive ┆ -9d2e-7be ┆ Services, ┆   ┆ Internati ┆ -86a0-484 ┆           ┆          │
│           ┆ s/e…      ┆ bbe…      ┆ In…       ┆   ┆ onal…     ┆ 8ba…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 149bcbac- ┆ PAI       ┆ … ┆ Payment   ┆ 678d9a28- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ c54b-5e31 ┆ Digital,  ┆   ┆ Alliance  ┆ b194-588f ┆           ┆          │
│ 9         ┆ v/Archive ┆ -b7d5-c38 ┆ LLC       ┆   ┆ Internati ┆ -86a0-484 ┆           ┆          │
│           ┆ s/e…      ┆ 138…      ┆           ┆   ┆ onal…     ┆ 8ba…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 2c29a49f- ┆ Brinks    ┆ … ┆ Brink’s,  ┆ 50e9123d- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 6d5b-5895 ┆ GroupI    ┆   ┆ Incorpora ┆ 6ad9-5c9a ┆           ┆          │
│ 9         ┆ v/Archive ┆ -b948-e37 ┆ LLC       ┆   ┆ ted       ┆ -b00a-656 ┆           ┆          │
│           ┆ s/e…      ┆ a96…      ┆           ┆   ┆           ┆ fd0…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ a3ed26c0- ┆ Brinks    ┆ … ┆ Brink’s,  ┆ 50e9123d- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ f17f-54cb ┆ GroupII   ┆   ┆ Incorpora ┆ 6ad9-5c9a ┆           ┆          │
│ 9         ┆ v/Archive ┆ -8546-f50 ┆ LLC       ┆   ┆ ted       ┆ -b00a-656 ┆           ┆          │
│           ┆ s/e…      ┆ 5ee…      ┆           ┆   ┆           ┆ fd0…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ b3559123- ┆ Brinks    ┆ … ┆ Brink’s,  ┆ 50e9123d- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ c6f5-5387 ┆ Group III ┆   ┆ Incorpora ┆ 6ad9-5c9a ┆           ┆          │
│ 9         ┆ v/Archive ┆ -807c-e55 ┆ LLC       ┆   ┆ ted       ┆ -b00a-656 ┆           ┆          │
│           ┆ s/e…      ┆ f03…      ┆           ┆   ┆           ┆ fd0…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 0782c92c- ┆ Brinks    ┆ … ┆ Brink’s,  ┆ 50e9123d- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 3d30-5eb5 ┆ Group IV  ┆   ┆ Incorpora ┆ 6ad9-5c9a ┆           ┆          │
│ 9         ┆ v/Archive ┆ -beed-d0d ┆ LLC       ┆   ┆ ted       ┆ -b00a-656 ┆           ┆          │
│           ┆ s/e…      ┆ 409…      ┆           ┆   ┆           ┆ fd0…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 12992af3- ┆ Brink’s   ┆ … ┆ Brink’s,  ┆ 50e9123d- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ a952-5ac4 ┆ Group V   ┆   ┆ Incorpora ┆ 6ad9-5c9a ┆           ┆          │
│ 9         ┆ v/Archive ┆ -a94b-3dc ┆ LLC       ┆   ┆ ted       ┆ -b00a-656 ┆           ┆          │
│           ┆ s/e…      ┆ d28…      ┆           ┆   ┆           ┆ fd0…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 0fb76fb5- ┆ Brink’s   ┆ … ┆ Pittston  ┆ b13312e2- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 6528-54c5 ┆ Group VI  ┆   ┆ Services  ┆ bcfd-521b ┆           ┆          │
│ 9         ┆ v/Archive ┆ -89d7-0e9 ┆ LLC       ┆   ┆ Group     ┆ -83f1-1ea ┆           ┆          │
│           ┆ s/e…      ┆ 50e…      ┆           ┆   ┆ Inc.      ┆ bed…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ e6384710- ┆ Brink’s   ┆ … ┆ Brink’s   ┆ 0fb76fb5- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ b2ae-5740 ┆ Express   ┆   ┆ Group VI  ┆ 6528-54c5 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -a314-608 ┆ Company   ┆   ┆ LLC       ┆ -89d7-0e9 ┆           ┆          │
│           ┆ s/e…      ┆ 2c8…      ┆           ┆   ┆           ┆ 50e…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 6eca143b- ┆ Brink’s   ┆ … ┆ Brink’s   ┆ 0fb76fb5- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 5dfb-5753 ┆ Global    ┆   ┆ Group VI  ┆ 6528-54c5 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -bc14-a23 ┆ Payments, ┆   ┆ LLC       ┆ -89d7-0e9 ┆           ┆          │
│           ┆ s/e…      ┆ 821…      ┆ LLC       ┆   ┆           ┆ 50e…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 09dae368- ┆ Brink’s   ┆ … ┆ Brink’s   ┆ 0fb76fb5- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ ccbb-58a5 ┆ Complete  ┆   ┆ Group VI  ┆ 6528-54c5 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -9aa9-6d8 ┆ Holding   ┆   ┆ LLC       ┆ -89d7-0e9 ┆           ┆          │
│           ┆ s/e…      ┆ 518…      ┆ Compa…    ┆   ┆           ┆ 50e…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ d6c680d1- ┆ Brink's   ┆ … ┆ Brink’s   ┆ 09dae368- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 5eee-5557 ┆ Capital   ┆   ┆ Complete  ┆ ccbb-58a5 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -8bf2-01c ┆ Mexico,   ┆   ┆ Holding   ┆ -9aa9-6d8 ┆           ┆          │
│           ┆ s/e…      ┆ 668…      ┆ S.A. d…   ┆   ┆ Compa…    ┆ 518…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ e00a5c06- ┆ Brink’s   ┆ … ┆ Brink’s   ┆ 0fb76fb5- ┆ 26.0      ┆          │
│ 902500005 ┆ ww.sec.go ┆ d46c-52c8 ┆ St. Lucia ┆   ┆ Group VI  ┆ 6528-54c5 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -a1ce-755 ┆ Ltd.      ┆   ┆ LLC       ┆ -89d7-0e9 ┆           ┆          │
│           ┆ s/e…      ┆ 87e…      ┆           ┆   ┆           ┆ 50e…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 06ff7ec1- ┆ Security  ┆ … ┆ Brink’s   ┆ 0fb76fb5- ┆ 95.0      ┆          │
│ 902500005 ┆ ww.sec.go ┆ 823c-5065 ┆ Services  ┆   ┆ Group VI  ┆ 6528-54c5 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -a0ef-e53 ┆ Company   ┆   ┆ LLC       ┆ -89d7-0e9 ┆           ┆          │
│           ┆ s/e…      ┆ 6cb…      ┆ Ltd       ┆   ┆           ┆ 50e…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 57d5b706- ┆ Servicio  ┆ … ┆ Brink’s   ┆ 0fb76fb5- ┆ 99.75     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 54ed-5aff ┆ Pan       ┆   ┆ Group VI  ┆ 6528-54c5 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -88fe-ba0 ┆ Americano ┆   ┆ LLC       ┆ -89d7-0e9 ┆           ┆          │
│           ┆ s/e…      ┆ 0cc…      ┆ de Prot…  ┆   ┆           ┆ 50e…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 4da13dd0- ┆ Inmobilia ┆ … ┆ Servicio  ┆ 57d5b706- ┆ 99.75     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 0a89-5c27 ┆ ria,      ┆   ┆ Pan       ┆ 54ed-5aff ┆           ┆          │
│ 9         ┆ v/Archive ┆ -80ef-8ab ┆ A.J.,     ┆   ┆ Americano ┆ -88fe-ba0 ┆           ┆          │
│           ┆ s/e…      ┆ a78…      ┆ S.A. de   ┆   ┆ de Prot…  ┆ 0cc…      ┆           ┆          │
│           ┆           ┆           ┆ C.…       ┆   ┆           ┆           ┆           ┆          │
│ `00000788 ┆ https://w ┆ f7dcb564- ┆ Operadora ┆ … ┆ null      ┆ 6efe832d- ┆ 99.75     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 086f-5b5b ┆ Especiali ┆   ┆           ┆ 6b6b-5802 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -bb83-27d ┆ zada de   ┆   ┆           ┆ -a8fb-92c ┆           ┆          │
│           ┆ s/e…      ┆ a42…      ┆ Tra…      ┆   ┆           ┆ aa2…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 07f912eb- ┆ Procesos  ┆ … ┆ null      ┆ 6efe832d- ┆ 99.75     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 34dc-5447 ┆ Integrale ┆   ┆           ┆ 6b6b-5802 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -8407-d19 ┆ s en      ┆   ┆           ┆ -a8fb-92c ┆           ┆          │
│           ┆ s/e…      ┆ 771…      ┆ Distrib…  ┆   ┆           ┆ aa2…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ a5e98573- ┆ Brink’s   ┆ … ┆ null      ┆ 6efe832d- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ a3a6-590a ┆ Security  ┆   ┆           ┆ 6b6b-5802 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -83e7-257 ┆ Internati ┆   ┆           ┆ -a8fb-92c ┆           ┆          │
│           ┆ s/e…      ┆ 013…      ┆ onal…     ┆   ┆           ┆ aa2…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 5fcda6c7- ┆ Brinks    ┆ … ┆ Brink’s   ┆ a5e98573- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 8427-51d1 ┆ Support   ┆   ┆ Security  ┆ a3a6-590a ┆           ┆          │
│ 9         ┆ v/Archive ┆ -851f-47d ┆ Services  ┆   ┆ Internati ┆ -83e7-257 ┆           ┆          │
│           ┆ s/e…      ┆ 94f…      ┆ Sdn. B…   ┆   ┆ onal…     ┆ 013…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 34154f2a- ┆ G4S Group ┆ … ┆ Brink’s   ┆ a5e98573- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 4d98-58f3 ┆ Holding   ┆   ┆ Security  ┆ a3a6-590a ┆           ┆          │
│ 9         ┆ v/Archive ┆ -9af0-8e0 ┆ Limited   ┆   ┆ Internati ┆ -83e7-257 ┆           ┆          │
│           ┆ s/e…      ┆ d3b…      ┆           ┆   ┆ onal…     ┆ 013…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 65b6a64d- ┆ Viva      ┆ … ┆ G4S Group ┆ 34154f2a- ┆ 100.0     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 9198-5c8d ┆ Powertech ┆   ┆ Holding   ┆ 4d98-58f3 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -a4a7-f3e ┆ Sdn. Bhd. ┆   ┆ Limited   ┆ -9af0-8e0 ┆           ┆          │
│           ┆ s/e…      ┆ 9cf…      ┆           ┆   ┆           ┆ d3b…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 63b3175a- ┆ Safeguard ┆ … ┆ G4S Group ┆ 34154f2a- ┆ 48.88     ┆          │
│ 902500005 ┆ ww.sec.go ┆ bafa-58c3 ┆ s Secure  ┆   ┆ Holding   ┆ 4d98-58f3 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -a0c1-b45 ┆ Solution  ┆   ┆ Limited   ┆ -9af0-8e0 ┆           ┆          │
│           ┆ s/e…      ┆ 5f7…      ┆ Sdn…      ┆   ┆           ┆ d3b…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 63b3175a- ┆ Safeguard ┆ … ┆ Safeguard ┆ 63b3175a- ┆ 48.88     ┆          │
│ 902500005 ┆ ww.sec.go ┆ bafa-58c3 ┆ s Secure  ┆   ┆ s Secure  ┆ bafa-58c3 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -a0c1-b45 ┆ Solution  ┆   ┆ Solution  ┆ -a0c1-b45 ┆           ┆          │
│           ┆ s/e…      ┆ 5f7…      ┆ Sdn…      ┆   ┆ Sdn…      ┆ 5f7…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 803cb870- ┆ Almo      ┆ … ┆ Safeguard ┆ 63b3175a- ┆ 48.88     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 8045-5116 ┆ Systems   ┆   ┆ s Secure  ┆ bafa-58c3 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -b4cc-bc4 ┆ Sdn Bhd   ┆   ┆ Solution  ┆ -a0c1-b45 ┆           ┆          │
│           ┆ s/e…      ┆ 6f1…      ┆           ┆   ┆ Sdn…      ┆ 5f7…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ 5ce95107- ┆ Group 4   ┆ … ┆ Safeguard ┆ 63b3175a- ┆ 48.88     ┆          │
│ 902500005 ┆ ww.sec.go ┆ afb7-5a02 ┆ Falck CMS ┆   ┆ s Secure  ┆ bafa-58c3 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -9868-738 ┆ Sdn Bhd   ┆   ┆ Solution  ┆ -a0c1-b45 ┆           ┆          │
│           ┆ s/e…      ┆ 3ca…      ┆           ┆   ┆ Sdn…      ┆ 5f7…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ ffd1f40a- ┆ Gwenkens  ┆ … ┆ Safeguard ┆ 63b3175a- ┆ 43.99     ┆          │
│ 902500005 ┆ ww.sec.go ┆ 883a-5e38 ┆ Security  ┆   ┆ s Secure  ┆ bafa-58c3 ┆           ┆          │
│ 9         ┆ v/Archive ┆ -84f9-cfa ┆ Services  ┆   ┆ Solution  ┆ -a0c1-b45 ┆           ┆          │
│           ┆ s/e…      ┆ ad7…      ┆ Sdn…      ┆   ┆ Sdn…      ┆ 5f7…      ┆           ┆          │
│ `00000788 ┆ https://w ┆ fa2cb7de- ┆ Safeguard ┆ … ┆ Gwenkens  ┆ ffd1f40a- ┆ 43.99     ┆          │

In [6]:
# Distribution of nesting levels
df.group_by("NestingLevel").agg(pl.count().alias("count")).sort("NestingLevel")

/var/folders/pg/rrvt9fgx479brk1wjwzw9bqc0000gn/T/ipykernel_42639/269099081.py:2: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  df.group_by("NestingLevel").agg(pl.count().alias("count")).sort("NestingLevel")

shape: (9, 2)
┌──────────────┬────────┐
│ NestingLevel ┆ count  │
│ ---          ┆ ---    │
│ i64          ┆ u32    │
╞══════════════╪════════╡
│ 0            ┆ 174450 │
│ 1            ┆ 3997   │
│ 2            ┆ 1117   │
│ 3            ┆ 577    │
│ 4            ┆ 216    │
│ 5            ┆ 88     │
│ 6            ┆ 92     │
│ 7            ┆ 18     │
│ 8            ┆ 15     │
└──────────────┴────────┘

In [7]:
# TODO: Find parent rows based on ParentId = SubsidiaryId
# (Commented out - we don't have SubsidiaryId column yet)

# nested_with_parents = nested.join(
#     df.select(["SubsidiaryId", "Subsidiary", "Jurisdiction"]).rename({"Subsidiary": "ParentSubsidiary", "Jurisdiction": "ParentJurisdiction"}),
#     left_on="ParentId",
#     right_on="SubsidiaryId",
#     how="left"
# )
# nested_with_parents

## 2. Rows with Footnotes

In [8]:
# Find rows with non-empty footnotes
with_footnotes = df.filter(
    pl.col("Footnotes").is_not_null() & (pl.col("Footnotes").str.strip_chars() != "")
)

footnotes_accessions = with_footnotes.select("Accession").unique()

print(f"Rows with footnotes: {len(with_footnotes):,}")
print(f"Percentage: {len(with_footnotes) / len(df) * 100:.1f}%")

print(f"\nUnique Accession list({len(footnotes_accessions)}):")
print(footnotes_accessions.to_series().to_list())
with_footnotes.head(20)

Rows with footnotes: 1,436
Percentage: 0.8%

Unique Accession list(202):
['`000081158925000008', '`000095017025042908', '`000121390025026215', '`000121390025043484', '`000117891325001365', '`000143774925004612', '`000007747625000007', '`000102085925000054', '`000103297525000029', '`000132619025000015', '`000100683725000021', '`000121390025043461', '`000164117225001513', '`000095017025030677', '`000121390025021907', '`000007628225000013', '`000110465925108504', '`000132440425000006', '`000162828025006093', '`000094667325000008', '`000084405925000009', '`000110465925123106', '`000141057825000783', '`000157587225000393', '`000009484525000005', '`000010956325000080', '`000153949725002331', '`000121390025037643', '`000000885825000028', '`000095017025045947', '`000118518525000229', '`000162828025011831', '`000149315225011033', '`000155837025001222', '`000105350725000025', '`000143774925005687', '`000152013825000162', '`000008812125000017', '`000164974925000035', '`000008596125000032', '`000009338925000012', '`000104013025000072', '`000155837025011776', '`000143774925029761', '`000182912625003270', '`000165495425004306', '`000121390025103497', '`000170160525000035', '`000132046125000033', '`000091197125000007', '`000095017025020763', '`000162828025019714', '`000116638825000014', '`000165072925000004', '`000141057825000623', '`000010416925000021', '`000095017025038754', '`000114036125009158', '`000158536425000014', '`000035603725000065', '`000089707725000007', '`000162828025005311', '`000182912625004113', '`000088461425000053', '`000164117225004712', '`000165495425012195', '`000078332425000008', '`000162828025005715', '`000130696525000007', '`000159036425000006', '`000168006225000003', '`000171126925000004', '`000162828025008128', '`000121390025020360', '`000162828025053207', '`000184908925000005', '`000173399825000020', '`000119312525097693', '`000007736025000006', '`000138865825000028', '`000095017025047918', '`000093905725000319', '`000190144025000012', '`000149315225014286', '`000006270925000015', '`000074026025000052', '`000007086625000010', '`000121390025037703', '`000095017025099742', '`000095017025026655', '`000162828025007110', '`000144889325000009', '`000143612625000026', '`000082441025000008', '`000121390025035604', '`000121390025041556', '`000143757825000007', '`000095017025023184', '`000119312525158722', '`000007528825000033', '`000114036125016487', '`000111505525000042', '`000101376225003193', '`000162828025015469', '`000008943925000010', '`000160402825000012', '`000107137125000053', '`000141057825000294', '`000162828025004879', '`000120717925000005', '`000008553525000012', '`000155837025003827', '`000095017025025644', '`000032001725000011', '`000143774925007559', '`000155837025003413', '`000101376225003608', '`000162828025037656', '`000095017025026108', '`000031920125000024', '`000007031825000009', '`000095017025023207', '`000071742325000006', '`000134287425000024', '`000151717525000002', '`000164841625000027', '`000165495425012190', '`000003696625000024', '`000162828025033105', '`000093796625000009', '`000155837025002417', '`000129281425001504', '`000118518525000706', '`000164117225001136', '`000164117225000737', '`000092480525000012', '`000110465925104454', '`000095017025027569', '`000093570325000015', '`000171218425000031', '`000095017025047901', '`000199771125000030', '`000164117225001193', '`000157791625000011', '`000071578725000006', '`000095017025024783', '`000182831825000057', '`000141057825001475', '`000149315225009391', '`000004021125000024', '`000141057825000689', '`000000248825000012', '`000162828025005126', '`000095017025059532', '`000005125325000013', '`000119312525118506', '`000106770125000008', '`000167128425000004', '`000137895025000036', '`000110465925121185', '`000162828025008767', '`000142322125000100', '`000155118225000006', '`000151029525000012', '`000155837025001224', '`000181838325000022', '`000093041325001069', '`000117891325000821', '`000095017025024750', '`000162529725000016', '`000112336025000011', '`000095017025070268', '`000091314425000009', '`000162828025008401', '`000102891825000014', '`000095017025078416', '`000197413825000016', '`000129281425001352', '`000169051125000011', '`000155837025001263', '`000117891325001126', '`000077149725000031', '`000155837025002409', '`000150446125000014', '`000151691225000064', '`000141057825001050', '`000003069725000003', '`000102312825000026', '`000191565725000019', '`000121390025043459', '`000121390025044284', '`000093905725000242', '`000091114725000010', '`000009212225000018', '`000000684525000049', '`000162828025007126', '`000121465925005928', '`000138119725000036', '`000000497725000047', '`000119312525284680', '`000117184325007594', '`000162828025045293']

shape: (20, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Accession ┆ URL       ┆ Subsidiar ┆ Subsidiar ┆ … ┆ ParentNam ┆ ParentId  ┆ Ownership ┆ Footnote │
│ ---       ┆ ---       ┆ yId       ┆ y         ┆   ┆ e         ┆ ---       ┆ ---       ┆ s        │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ f64       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ `00014931 ┆ https://w ┆ ae3a6023- ┆ Brigadier ┆ … ┆ null      ┆ a1d1ae4e- ┆ 100.0     ┆ 2000     │
│ 522501428 ┆ ww.sec.go ┆ d887-54c3 ┆ Security  ┆   ┆           ┆ 7f40-5345 ┆           ┆          │
│ 6         ┆ v/Archive ┆ -a9a1-d20 ┆ Systems   ┆   ┆           ┆ -a808-c76 ┆           ┆          │
│           ┆ s/e…      ┆ d99…      ┆ Ltd…      ┆   ┆           ┆ c87…      ┆           ┆          │
│ `00010068 ┆ https://w ┆ f983a1d0- ┆ DBM       ┆ … ┆ HC2 Broad ┆ 03eb6c1c- ┆ 42.35     ┆ 2        │
│ 372500002 ┆ ww.sec.go ┆ ab99-5a2b ┆ Global    ┆   ┆ casting   ┆ 5330-53db ┆           ┆          │
│ 1         ┆ v/Archive ┆ -b1ae-c56 ┆ Inc.      ┆   ┆ Inc.      ┆ -8db9-e74 ┆           ┆          │
│           ┆ s/e…      ┆ bf8…      ┆           ┆   ┆           ┆ a9c…      ┆           ┆          │
│ `00010068 ┆ https://w ┆ 3ea84c1a- ┆ GrayWolf  ┆ … ┆ CBHorn    ┆ ef581957- ┆ 51.0      ┆ 3, 4     │
│ 372500002 ┆ ww.sec.go ┆ d2dd-5b6d ┆ Industria ┆   ┆ Holdings, ┆ e49b-5501 ┆           ┆          │
│ 1         ┆ v/Archive ┆ -9350-9ee ┆ l, Inc.   ┆   ┆ Inc.      ┆ -bf26-4bc ┆           ┆          │
│           ┆ s/e…      ┆ 4c8…      ┆           ┆   ┆           ┆ fcc…      ┆           ┆          │
│ `00010068 ┆ https://w ┆ d4f565ce- ┆ GrayWolf  ┆ … ┆ GrayWolf  ┆ 3ea84c1a- ┆ 69.22     ┆ 5        │
│ 372500002 ┆ ww.sec.go ┆ 4080-50d5 ┆ Integrate ┆   ┆ Industria ┆ d2dd-5b6d ┆           ┆          │
│ 1         ┆ v/Archive ┆ -bc35-f37 ┆ d Constru ┆   ┆ l, Inc.   ┆ -9350-9ee ┆           ┆          │
│           ┆ s/e…      ┆ c57…      ┆ cti…      ┆   ┆           ┆ 4c8…      ┆           ┆          │
│ `00010068 ┆ https://w ┆ 9a321b95- ┆ Midwest   ┆ … ┆ GrayWolf  ┆ 3ea84c1a- ┆ 100.0     ┆ 6        │
│ 372500002 ┆ ww.sec.go ┆ 1e2f-59a4 ┆ Environme ┆   ┆ Industria ┆ d2dd-5b6d ┆           ┆          │
│ 1         ┆ v/Archive ┆ -a8a8-a4d ┆ ntal,     ┆   ┆ l, Inc.   ┆ -9350-9ee ┆           ┆          │
│           ┆ s/e…      ┆ 473…      ┆ Inc.      ┆   ┆           ┆ 4c8…      ┆           ┆          │
│ `00010068 ┆ https://w ┆ 49b48c7b- ┆ Milco     ┆ … ┆ GrayWolf  ┆ 3ea84c1a- ┆ 100.0     ┆ 7        │
│ 372500002 ┆ ww.sec.go ┆ 54c5-5814 ┆ National  ┆   ┆ Industria ┆ d2dd-5b6d ┆           ┆          │
│ 1         ┆ v/Archive ┆ -ac82-cba ┆ Construct ┆   ┆ l, Inc.   ┆ -9350-9ee ┆           ┆          │
│           ┆ s/e…      ┆ f13…      ┆ ors, I…   ┆   ┆           ┆ 4c8…      ┆           ┆          │
│ `00010068 ┆ https://w ┆ e046aa9f- ┆ DBM       ┆ … ┆ DBM       ┆ 745dffea- ┆ 100.0     ┆ 8        │
│ 372500002 ┆ ww.sec.go ┆ b5c3-5f78 ┆ Vircon    ┆   ┆ Global    ┆ bbc2-5486 ┆           ┆          │
│ 1         ┆ v/Archive ┆ -9b05-59b ┆ Services  ┆   ┆ North     ┆ -af3c-399 ┆           ┆          │
│           ┆ s/e…      ┆ fa9…      ┆ , Inc.    ┆   ┆ America   ┆ ef0…      ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ Inc.      ┆           ┆           ┆          │
│ `00010068 ┆ https://w ┆ f8018534- ┆ Schuff    ┆ … ┆ DBM       ┆ 745dffea- ┆ 100.0     ┆ 9        │
│ 372500002 ┆ ww.sec.go ┆ 6f22-5888 ┆ Steel     ┆   ┆ Global    ┆ bbc2-5486 ┆           ┆          │
│ 1         ┆ v/Archive ┆ -9318-653 ┆ Company   ┆   ┆ North     ┆ -af3c-399 ┆           ┆          │
│           ┆ s/e…      ┆ 587…      ┆           ┆   ┆ America   ┆ ef0…      ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ Inc.      ┆           ┆           ┆          │
│ `00010068 ┆ https://w ┆ 02dfd234- ┆ Derr and  ┆ … ┆ Schuff    ┆ f8018534- ┆ 100.0     ┆ 10       │
│ 372500002 ┆ ww.sec.go ┆ dd92-5703 ┆ Isbell    ┆   ┆ Steel     ┆ 6f22-5888 ┆           ┆          │
│ 1         ┆ v/Archive ┆ -9b9a-ada ┆ Construct ┆   ┆ Company   ┆ -9318-653 ┆           ┆          │
│           ┆ s/e…      ┆ fbd…      ┆ ion, …    ┆   ┆           ┆ 587…      ┆           ┆          │
│ `00010068 ┆ https://w ┆ 80addfb6- ┆ Innovativ ┆ … ┆ Innovativ ┆ 80addfb6- ┆ 100.0     ┆ 11       │
│ 372500002 ┆ ww.sec.go ┆ 2e06-5b1c ┆ e Enginee ┆   ┆ e Enginee ┆ 2e06-5b1c ┆           ┆          │
│ 1         ┆ v/Archive ┆ -a41d-8f7 ┆ ring      ┆   ┆ ring      ┆ -a41d-8f7 ┆           ┆          │
│           ┆ s/e…      ┆ 569…      ┆ Solutio…  ┆   ┆ Solutio…  ┆ 569…      ┆           ┆          │
│ `00010068 ┆ https://w ┆ 25eabc9e- ┆ Memco LLC ┆ … ┆ US        ┆ 3f3be104- ┆ 100.0     ┆ 12       │
│ 372500002 ┆ ww.sec.go ┆ 9763-5d44 ┆           ┆   ┆ Erectors  ┆ b481-5d9d ┆           ┆          │
│ 1         ┆ v/Archive ┆ -91c3-259 ┆           ┆   ┆ LLC       ┆ -82ef-e40 ┆           ┆          │
│           ┆ s/e…      ┆ b6e…      ┆           ┆   ┆           ┆ c16…      ┆           ┆          │
│ `00010068 ┆ https://w ┆ dc94838d- ┆ DBM       ┆ … ┆ DBM       ┆ f2224a0d- ┆ 69.22     ┆ 13       │
│ 372500002 ┆ ww.sec.go ┆ dfff-5566 ┆ Vircon    ┆   ┆ Global    ┆ 37b3-5722 ┆           ┆          │
│ 1         ┆ v/Archive ┆ -b67a-dcb ┆ Services  ┆   ┆ Holdings  ┆ -bce9-f22 ┆           ┆          │
│           ┆ s/e…      ┆ 313…      ┆ LTD       ┆   ┆ Inc.      ┆ 7fd…      ┆           ┆          │
│ `00010068 ┆ https://w ┆ 75762f58- ┆ DTV       ┆ … ┆ HC2 Broad ┆ 03eb6c1c- ┆ 100.0     ┆ 14       │
│ 372500002 ┆ ww.sec.go ┆ 8ee9-5210 ┆ America   ┆   ┆ casting   ┆ 5330-53db ┆           ┆          │
│ 1         ┆ v/Archive ┆ -b520-233 ┆ Corporati ┆   ┆ Inc.      ┆ -8db9-e74 ┆           ┆          │
│           ┆ s/e…      ┆ cc2…      ┆ on        ┆   ┆           ┆ a9c…      ┆           ┆          │
│ `00010068 ┆ https://w ┆ 19715c56- ┆ R2 Techno ┆ … ┆ Pansend   ┆ a224026b- ┆ 100.0     ┆ 15       │
│ 372500002 ┆ ww.sec.go ┆ 5791-5a90 ┆ logies,   ┆   ┆ Life      ┆ bdf7-509e ┆           ┆          │
│ 1         ┆ v/Archive ┆ -afdf-83a ┆ Inc.      ┆   ┆ Sciences, ┆ -828f-98f ┆           ┆          │
│           ┆ s/e…      ┆ c07…      ┆           ┆   ┆ LLC       ┆ 720…      ┆           ┆          │
│ `00009390 ┆ https://w ┆ f5bb69d5- ┆ Provident ┆ … ┆ Provident ┆ 8e9ff00b- ┆ 100.0     ┆ 1        │
│ 572500024 ┆ ww.sec.go ┆ 2402-5a92 ┆ Financial ┆   ┆ Savings   ┆ 8dfa-57f1 ┆           ┆          │
│ 2         ┆ v/Archive ┆ -8bc4-972 ┆ Corp      ┆   ┆ Bank,     ┆ -894e-bba ┆           ┆          │
│           ┆ s/e…      ┆ 748…      ┆           ┆   ┆ F.S.B.    ┆ 546…      ┆           ┆          │
│ `00009390 ┆ https://w ┆ f74ad826- ┆ Profed    ┆ … ┆ Provident ┆ 8e9ff00b- ┆ 100.0     ┆ 1, 2     │
│ 572500024 ┆ ww.sec.go ┆ a03d-56b3 ┆ Mortgage, ┆   ┆ Savings   ┆ 8dfa-57f1 ┆           ┆          │
│ 2         ┆ v/Archive ┆ -ad14-1e4 ┆ Inc.      ┆   ┆ Bank,     ┆ -894e-bba ┆           ┆          │
│           ┆ s/e…      ┆ 123…      ┆           ┆   ┆ F.S.B.    ┆ 546…      ┆           ┆          │
│ `00009390 ┆ https://w ┆ c1a5911a- ┆ First     ┆ … ┆ Provident ┆ 8e9ff00b- ┆ 100.0     ┆ 1, 2     │
│ 572500024 ┆ ww.sec.go ┆ c7d6-52e5 ┆ Service   ┆   ┆ Savings   ┆ 8dfa-57f1 ┆           ┆          │
│ 2         ┆ v/Archive ┆ -8650-9af ┆ Corporati ┆   ┆ Bank,     ┆ -894e-bba ┆           ┆          │
│           ┆ s/e…      ┆ 4c8…      ┆ on        ┆   ┆ F.S.B.    ┆ 546…      ┆           ┆          │
│ `00010208 ┆ https://w ┆ 6a3f29fd- ┆ Aries     ┆ … ┆ SUPERVALU ┆ 3d374007- ┆ 100.0     ┆ 1        │
│ 592500005 ┆ ww.sec.go ┆ a44c-5a4b ┆ Portfolio ┆   ┆ INC.      ┆ 4d4a-59a4 ┆           ┆          │
│ 4         ┆ v/Archive ┆ -976f-5ea ┆ 2025, LLC ┆   ┆           ┆ -a960-619 ┆           ┆          │
│           ┆ s/e…      ┆ 673…      ┆           ┆   ┆           ┆ 497…      ┆           ┆          │
│ `00010208 ┆ https://w ┆ 429944bb- ┆ Blaine    ┆ … ┆ null      ┆ 81a08096- ┆ 100.0     ┆ 1        │
│ 592500005 ┆ ww.sec.go ┆ 39d9-5edc ┆ North     ┆   ┆           ┆ b757-52d9 ┆           ┆          │
│ 4         ┆ v/Archive ┆ -8975-f46 ┆ 1996      ┆   ┆           ┆ -a92c-233 ┆           ┆          │
│           ┆ s/e…      ┆ b17…      ┆ L.L.C.    ┆   ┆           ┆ e83…      ┆           ┆          │
│ `00010208 ┆ https://w ┆ f5078106- ┆ Bloomingt ┆ … ┆ null      ┆ 81a08096- ┆ 100.0     ┆ 2        │
│ 592500005 ┆ ww.sec.go ┆ 0af0-5999 ┆ on 1998   ┆   ┆           ┆ b757-52d9 ┆           ┆          │
│ 4         ┆ v/Archive ┆ -8a30-d65 ┆ L.L.C.    ┆   ┆           ┆ -a92c-233 ┆           ┆          │
│           ┆ s/e…      ┆ 510…      ┆           ┆   ┆           ┆ e83…      ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
# Unique footnote values per accession
footnotes_by_accession = df.filter(
    pl.col("Footnotes").is_not_null() & (pl.col("Footnotes").str.strip_chars() != "")
).group_by("Accession").agg(
    pl.col("Footnotes").unique().alias("UniqueFootnotes")
)

print(f"Accessions with footnotes: {len(footnotes_by_accession)}")
print(f"\nAccession: Footnotes")
for row in footnotes_by_accession.iter_rows():
    print(f"{row[0]}: {row[1]}")

Accessions with footnotes: 202

Accession: Footnotes
`000007528825000033: ['1', '2', '3', '4', '5', '6', '7', '8']
`000162828025008128: ['01', '02']
`000121390025041556: ['1', '2, 3', '4']
`000093905725000242: ['1', '1, 2']
`000170160525000035: ['1']
`000003069725000003: ['1']
`000094667325000008: ['1', '2']
`000162828025045293: ['2009']
`000000885825000028: ['2008']
`000005125325000013: ['1', '2', '3', '4', '5', '1990', '6', '7', '8']
`000110465925104454: ['1', '2', '3', '4']
`000144889325000009: ['1', '2', '3', '4', '5', '6', '7, 12', '7', '8', '9', '10', '11']
`000197413825000016: ['2010']
`000119312525158722: ['1', '2', '3', '4', '5']
`000110465925108504: ['2']
`000121390025044284: ['1']
`000104013025000072: ['2']
`000003696625000024: ['2', '3']
`000071742325000006: ['1', '1, 2', '2', '3', '4', '5', '6']
`000101376225003608: ['1', '2', '3', '4']
`000106770125000008: ['1', '2']
`000102891825000014: ['2']
`000121390025037703: ['1', '2', '3', '4', '5']
`000162828025019714: ['1']
`000141057825000783: ['1', '2', '3', '4', '5']
`000116638825000014: ['1']
`000095017025045947: ['1']
`000088461425000053: ['1', '3, 4, 5, 2']
`000182912625003270: ['1', '2', '3', '4', '5']
`000171126925000004: ['2']
`000007031825000009: ['1']
`000162828025008767: ['1']
`000102312825000026: ['1997']
`000155837025001224: ['1998']
`000084405925000009: ['1', '2']
`000143774925005687: ['1', '2']
`000095017025020763: ['4']
`000155837025002409: ['2', '2, 3, 4', '4', '5']
`000121390025021907: ['1', '2', '3']
`000155837025011776: ['1', '2', '3', '4', '5']
`000092480525000012: ['1', '2', '3', '4', '5', '6']
`000118518525000229: ['2']
`000168006225000003: ['1']
`000000497725000047: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17']
`000152013825000162: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
`000141057825000623: ['1', '2', '3', '4', '5', '6']
`000105350725000025: ['2', '3', '5', '1', '6', '4']
`000141057825001050: ['1', '2']
`000093041325001069: ['1', '2', '3', '4', '5', '6', '7', '8', '4, 7', '4, 8', '9', '10', '11', '12']
`000157791625000011: ['1', '2', '3', '4', '5', '6', '7', '8']
`000162828025005715: ['43', '23', '1']
`000132046125000033: ['2', '3']
`000095017025047918: ['2', '3', '4']
`000150446125000014: ['1', '2', '3', '4']
`000095017025023207: ['1990']
`000095017025038754: ['1']
`000149315225014286: ['2000']
`000103297525000029: ['1']
`000031920125000024: ['1992', '1987', '2002']
`000095017025024783: ['1']
`000129281425001352: ['1', '3']
`000162828025011831: ['1', '2', '3', '4', '5']
`000071578725000006: ['2', '3', '4', '5', '6']
`000100683725000021: ['2', '3, 4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15']
`000117184325007594: ['1', '2', '3']
`000035603725000065: ['1']
`000121390025035604: ['2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23']
`000164117225000737: ['150']
`000121390025043484: ['1', '2']
`000162828025007126: ['1', '2']
`000162828025005311: ['2008']
`000160402825000012: ['1', '2', '3', '4', '5', '6']
`000095017025026655: ['1', '2']
`000151691225000064: ['1']
`000157587225000393: ['1', '6', '12', '10', '7', '15', '3', '4', '8', '9', '11', '2, 10, 14', '2, 10', '13', '5']
`000007628225000013: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
`000078332425000008: ['1', '2', '3']
`000008596125000032: ['1', '2', '3', '4, 5', '6, 7, 8', '9', '10']
`000121390025037643: ['2014']
`000006270925000015: ['2005', '1999']
`000093905725000319: ['1']
`000081158925000008: ['1']
`000117891325001365: ['1']
`000119312525284680: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '13', '44', '16', '17', '11', '12', '18', '19', '20', '21', '23', '24', '25', '26', '27', '28', '29', '30', '31', '33', '34', '37', '38', '39', '15', '40', '42', '36', '45', '46', '47', '32', '35', '52', '50', '51', '41']
`000008943925000010: ['7', '5', '8', '6', '1', '2', '4', '3']
`000199771125000030: ['1', '2', '3', '4', '5']
`000129281425001504: ['1', '2', '3']
`000120717925000005: ['1', '2']
`000143774925029761: ['1', '2', '3', '4', '5', '6', '7', '8']
`000141057825001475: ['3', '4', '5', '6', '7', '8', '9', '25262', '10', '11', '12', '561', '662', '25092', '25093', '13', '14', '15', '16', '17', '20', '19']
`000162828025008401: ['2']
`000134287425000024: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24']
`000091314425000009: ['1', '2', '3', '4', '5', '6']
`000164841625000027: ['1', '2', '3, 4']
`000117891325000821: ['1998', '2013']
`000162828025004879: ['1']
`000095017025030677: ['1']
`000121465925005928: ['1']
`000132440425000006: ['3']
`000093796625000009: ['2001']
`000093570325000015: ['1', '2']
`000119312525118506: ['1, 2', '3', '4', '5', '6', '7']
`000095017025078416: ['1', '2']
`000107137125000053: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '2, 13', '3, 13', '14', '15', '16', '17', '18', '19', '20', '21', '22']
`000171218425000031: ['2015']
`000009212225000018: ['2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21']
`000111505525000042: ['2', '3', '4', '5', '6', '7', '8']
`000095017025042908: ['1', '2']
`000095017025026108: ['1']
`000074026025000052: ['2023']
`000007747625000007: ['2018']
`000184908925000005: ['160']
`000010956325000080: ['1976']
`000162828025015469: ['1']
`000159036425000006: ['2025']
`000004021125000024: ['1', '2', '1, 2', '3', '4', '5']
`000114036125009158: ['1']
`000143774925007559: ['1', '2', '3']
`000118518525000706: ['1', '2']
`000091114725000010: ['1', '2', '3']
`000121390025026215: ['1', '2', '3', '4', '5']
`000000684525000049: ['1', '5', '8', '3', '7', '11', '4', '10', '12', '9', '6', '2']
`000121390025020360: ['2001']
`000165495425012190: ['1', '2']
`000121390025043459: ['2009']
`000167128425000004: ['1']
`000191565725000019: ['1', '2', '3']
`000095017025099742: ['1', '2', '3', '4', '5', '6']
`000143757825000007: ['1', '2']
`000181838325000022: ['1', '2']
`000141057825000294: ['1']
`000149315225011033: ['1']
`000138119725000036: ['1', '2', '3']
`000182831825000057: ['1']
`000077149725000031: ['2014', '2010']
`000132619025000015: ['1']
`000143612625000026: ['1']
`000155118225000006: ['2012']
`000182912625004113: ['1', '2', '3', '4', '5']
`000117891325001126: ['1', '3', '4', '5', '6']
`000143774925004612: ['1', '4', '2', '3', '14', '5', '15', '10', '9', '12', '13', '16', '6', '7', '8', '11', '17']
`000095017025024750: ['2', '3', '4', '5']
`000095017025059532: ['1', '2']
`000095017025023184: ['1']
`000130696525000007: ['100', '101', '102', '103', '107', '82', '84', '89', '92', '93', '94', '96', '99', '4', '2']
`000137895025000036: ['1', '2']
`000141057825000689: ['1', '2', '3', '4', '5', '6', '7']
`000112336025000011: ['1', '2']
`000008812125000017: ['1']
`000164117225001136: ['1']
`000158536425000014: ['2003']
`000089707725000007: ['1', '2', '3', '8', '4', '1954, 5', '13', '6', '7', '9', '10', '11', '12']
`000162828025033105: ['1', '2', '3', '4', '5', '6']
`000032001725000011: ['2']
`000121390025103497: ['2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31']
`000162828025006093: ['2003', '1994']
`000164974925000035: ['1']
`000142322125000100: ['2']
`000095017025025644: ['1']
`000155837025002417: ['2', '3']
`000082441025000008: ['1']
`000138865825000028: ['1']
`000091197125000007: ['1']
`000119312525097693: ['1993', '1984']
`000165495425004306: ['1', '2', '3']
`000110465925121185: ['1', '2']
`000162828025037656: ['1']
`000162828025005126: ['2024']
`000110465925123106: ['1']
`000121390025043461: ['1983', '1997']
`000155837025001263: ['1']
`000095017025070268: ['1', '2', '3', '4', '5', '6']
`000151029525000012: ['1']
`000162828025007110: ['2']
`000190144025000012: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11']
`000162529725000016: ['2014', '2021']
`000155837025003827: ['1']
`000009338925000012: ['29']
`000165072925000004: ['1']
`000007736025000006: ['1', '2', '3', '4', '5', '6']
`000165495425012195: ['1, 2', '3', '4', '2', '5', '1']
`000151717525000002: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18']
`000102085925000054: ['1', '2']
`000095017025027569: ['2001']
`000164117225001193: ['1']
`000155837025003413: ['1', '2, 15', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13, 15', '14', '14, 15', '16', '17', '18', '19', '20', '21']
`000101376225003193: ['1982']
`000010416925000021: ['1']
`000149315225009391: ['1', '2', '3']
`000007086625000010: ['1985']
`000008553525000012: ['1']
`000114036125016487: ['1']
`000095017025047901: ['1', '2', '3']
`000155837025001222: ['10']
`000173399825000020: ['1']
`000000248825000012: ['1', '2', '26', '3', '23', '6', '7', '8', '9', '10', '11', '12', '13', '5', '4', '28', '14', '15', '25', '24', '16', '17', '18', '19', '20', '29', '27', '22', '21']
`000164117225004712: ['1', '2']
`000009484525000005: ['1']
`000153949725002331: ['1']
`000162828025053207: ['2007']
`000164117225001513: ['1', '2', '3']
`000169051125000011: ['1']

In [10]:
# Unique footnote values - extract all individual numbers with their accessions
import re

footnotes_with_accession = df.filter(
    pl.col("Footnotes").is_not_null() & (pl.col("Footnotes").str.strip_chars() != "")
).select(["Accession", "Footnotes"]).unique()

# Build a dict: number -> list of accessions
number_to_accessions = {}
for row in footnotes_with_accession.iter_rows():
    accession, footnote = row
    nums = re.findall(r'\d+', footnote)
    for n in nums:
        num = int(n)
        if num not in number_to_accessions:
            number_to_accessions[num] = set()
        number_to_accessions[num].add(accession)

# Sort by number descending and print
sorted_items = sorted(number_to_accessions.items(), key=lambda x: x[0], reverse=True)

print(f"Total unique footnote numbers: {len(sorted_items)}")
print(f"\nFootnoteNumber: Accessions")
for num, accs in sorted_items:
    print(f"{num}: {list(accs)}")

Total unique footnote numbers: 102

FootnoteNumber: Accessions
25262: ['`000141057825001475']
25093: ['`000141057825001475']
25092: ['`000141057825001475']
2025: ['`000159036425000006']
2024: ['`000162828025005126']
2023: ['`000074026025000052']
2021: ['`000162529725000016']
2018: ['`000007747625000007']
2015: ['`000171218425000031']
2014: ['`000162529725000016', '`000121390025037643', '`000077149725000031']
2013: ['`000117891325000821']
2012: ['`000155118225000006']
2010: ['`000197413825000016', '`000077149725000031']
2009: ['`000162828025045293', '`000121390025043459']
2008: ['`000000885825000028', '`000162828025005311']
2007: ['`000162828025053207']
2005: ['`000006270925000015']
2003: ['`000158536425000014', '`000162828025006093']
2002: ['`000031920125000024']
2001: ['`000121390025020360', '`000095017025027569', '`000093796625000009']
2000: ['`000149315225014286']
1999: ['`000006270925000015']
1998: ['`000155837025001224', '`000117891325000821']
1997: ['`000121390025043461', '`000102312825000026']
1994: ['`000162828025006093']
1993: ['`000119312525097693']
1992: ['`000031920125000024']
1990: ['`000095017025023207', '`000005125325000013']
1987: ['`000031920125000024']
1985: ['`000007086625000010']
1984: ['`000119312525097693']
1983: ['`000121390025043461']
1982: ['`000101376225003193']
1976: ['`000010956325000080']
1954: ['`000089707725000007']
662: ['`000141057825001475']
561: ['`000141057825001475']
160: ['`000184908925000005']
150: ['`000164117225000737']
107: ['`000130696525000007']
103: ['`000130696525000007']
102: ['`000130696525000007']
101: ['`000130696525000007']
100: ['`000130696525000007']
99: ['`000130696525000007']
96: ['`000130696525000007']
94: ['`000130696525000007']
93: ['`000130696525000007']
92: ['`000130696525000007']
89: ['`000130696525000007']
84: ['`000130696525000007']
82: ['`000130696525000007']
52: ['`000119312525284680']
51: ['`000119312525284680']
50: ['`000119312525284680']
47: ['`000119312525284680']
46: ['`000119312525284680']
45: ['`000119312525284680']
44: ['`000119312525284680']
43: ['`000162828025005715']
42: ['`000119312525284680']
41: ['`000119312525284680']
40: ['`000119312525284680']
39: ['`000119312525284680']
38: ['`000119312525284680']
37: ['`000119312525284680']
36: ['`000119312525284680']
35: ['`000119312525284680']
34: ['`000119312525284680']
33: ['`000119312525284680']
32: ['`000119312525284680']
31: ['`000119312525284680', '`000121390025103497']
30: ['`000121390025103497', '`000119312525284680']
29: ['`000119312525284680', '`000009338925000012', '`000121390025103497', '`000000248825000012']
28: ['`000000248825000012', '`000121390025103497', '`000119312525284680']
27: ['`000119312525284680', '`000121390025103497', '`000000248825000012']
26: ['`000000248825000012', '`000121390025103497', '`000119312525284680']
25: ['`000000248825000012', '`000121390025103497', '`000119312525284680']
24: ['`000119312525284680', '`000121390025103497', '`000000248825000012', '`000134287425000024']
23: ['`000162828025005715', '`000119312525284680', '`000121390025103497', '`000134287425000024', '`000121390025035604', '`000000248825000012']
22: ['`000121390025103497', '`000134287425000024', '`000107137125000053', '`000121390025035604', '`000000248825000012']
21: ['`000009212225000018', '`000155837025003413', '`000119312525284680', '`000121390025103497', '`000134287425000024', '`000107137125000053', '`000121390025035604', '`000000248825000012']
20: ['`000009212225000018', '`000155837025003413', '`000121390025103497', '`000119312525284680', '`000134287425000024', '`000141057825001475', '`000107137125000053', '`000121390025035604', '`000000248825000012']
19: ['`000009212225000018', '`000155837025003413', '`000121390025103497', '`000119312525284680', '`000134287425000024', '`000141057825001475', '`000107137125000053', '`000121390025035604', '`000000248825000012']
18: ['`000009212225000018', '`000155837025003413', '`000119312525284680', '`000121390025103497', '`000134287425000024', '`000151717525000002', '`000107137125000053', '`000121390025035604', '`000000248825000012']
17: ['`000009212225000018', '`000155837025003413', '`000000497725000047', '`000121390025103497', '`000119312525284680', '`000134287425000024', '`000143774925004612', '`000151717525000002', '`000141057825001475', '`000107137125000053', '`000121390025035604', '`000000248825000012']
16: ['`000009212225000018', '`000155837025003413', '`000000497725000047', '`000119312525284680', '`000121390025103497', '`000134287425000024', '`000143774925004612', '`000151717525000002', '`000141057825001475', '`000107137125000053', '`000121390025035604', '`000000248825000012']
15: ['`000009212225000018', '`000155837025003413', '`000000497725000047', '`000119312525284680', '`000121390025103497', '`000157587225000393', '`000134287425000024', '`000143774925004612', '`000100683725000021', '`000141057825001475', '`000107137125000053', '`000151717525000002', '`000121390025035604', '`000000248825000012']
14: ['`000009212225000018', '`000155837025003413', '`000000497725000047', '`000121390025103497', '`000157587225000393', '`000134287425000024', '`000143774925004612', '`000151717525000002', '`000141057825001475', '`000107137125000053', '`000100683725000021', '`000121390025035604', '`000000248825000012']
13: ['`000009212225000018', '`000155837025003413', '`000000497725000047', '`000089707725000007', '`000119312525284680', '`000157587225000393', '`000134287425000024', '`000121390025103497', '`000143774925004612', '`000100683725000021', '`000141057825001475', '`000107137125000053', '`000151717525000002', '`000121390025035604', '`000000248825000012']
12: ['`000009212225000018', '`000155837025003413', '`000151717525000002', '`000000497725000047', '`000000248825000012', '`000089707725000007', '`000119312525284680', '`000121390025103497', '`000134287425000024', '`000144889325000009', '`000157587225000393', '`000143774925004612', '`000100683725000021', '`000141057825001475', '`000107137125000053', '`000093041325001069', '`000121390025035604', '`000000684525000049']
11: ['`000009212225000018', '`000155837025003413', '`000000248825000012', '`000089707725000007', '`000119312525284680', '`000121390025103497', '`000143774925004612', '`000093041325001069', '`000121390025035604', '`000000684525000049', '`000157587225000393', '`000151717525000002', '`000141057825001475', '`000000497725000047', '`000134287425000024', '`000144889325000009', '`000190144025000012', '`000100683725000021', '`000107137125000053']
10: ['`000009212225000018', '`000155837025003413', '`000000248825000012', '`000007628225000013', '`000089707725000007', '`000121390025103497', '`000119312525284680', '`000143774925004612', '`000093041325001069', '`000121390025035604', '`000008596125000032', '`000000684525000049', '`000157587225000393', '`000152013825000162', '`000151717525000002', '`000141057825001475', '`000000497725000047', '`000134287425000024', '`000144889325000009', '`000155837025001222', '`000190144025000012', '`000100683725000021', '`000107137125000053']
9: ['`000009212225000018', '`000155837025003413', '`000000248825000012', '`000007628225000013', '`000089707725000007', '`000119312525284680', '`000121390025103497', '`000143774925004612', '`000093041325001069', '`000121390025035604', '`000008596125000032', '`000000684525000049', '`000157587225000393', '`000152013825000162', '`000151717525000002', '`000141057825001475', '`000000497725000047', '`000134287425000024', '`000144889325000009', '`000190144025000012', '`000100683725000021', '`000107137125000053']
8: ['`000009212225000018', '`000155837025003413', '`000000248825000012', '`000008943925000010', '`000007628225000013', '`000089707725000007', '`000119312525284680', '`000007528825000033', '`000121390025103497', '`000143774925004612', '`000093041325001069', '`000121390025035604', '`000008596125000032', '`000000684525000049', '`000157791625000011', '`000143774925029761', '`000157587225000393', '`000152013825000162', '`000151717525000002', '`000141057825001475', '`000000497725000047', '`000005125325000013', '`000134287425000024', '`000144889325000009', '`000190144025000012', '`000100683725000021', '`000107137125000053', '`000111505525000042']
7: ['`000009212225000018', '`000155837025003413', '`000119312525118506', '`000000248825000012', '`000008943925000010', '`000007628225000013', '`000089707725000007', '`000119312525284680', '`000121390025103497', '`000007528825000033', '`000143774925004612', '`000093041325001069', '`000121390025035604', '`000008596125000032', '`000000684525000049', '`000157791625000011', '`000143774925029761', '`000157587225000393', '`000141057825000689', '`000152013825000162', '`000151717525000002', '`000141057825001475', '`000000497725000047', '`000005125325000013', '`000134287425000024', '`000144889325000009', '`000190144025000012', '`000100683725000021', '`000107137125000053', '`000111505525000042']
6: ['`000009212225000018', '`000155837025003413', '`000007736025000006', '`000119312525118506', '`000095017025099742', '`000141057825000623', '`000000248825000012', '`000008943925000010', '`000007628225000013', '`000089707725000007', '`000119312525284680', '`000007528825000033', '`000121390025103497', '`000091314425000009', '`000143774925004612', '`000093041325001069', '`000121390025035604', '`000008596125000032', '`000000684525000049', '`000157791625000011', '`000071578725000006', '`000160402825000012', '`000143774925029761', '`000092480525000012', '`000157587225000393', '`000162828025033105', '`000141057825000689', '`000105350725000025', '`000152013825000162', '`000151717525000002', '`000141057825001475', '`000071742325000006', '`000000497725000047', '`000005125325000013', '`000117891325001126', '`000134287425000024', '`000144889325000009', '`000095017025070268', '`000190144025000012', '`000100683725000021', '`000107137125000053', '`000111505525000042']
5: ['`000009212225000018', '`000155837025003413', '`000007736025000006', '`000119312525118506', '`000155837025002409', '`000095017025099742', '`000141057825000623', '`000121390025037703', '`000155837025011776', '`000000248825000012', '`000008943925000010', '`000004021125000024', '`000007628225000013', '`000089707725000007', '`000119312525284680', '`000007528825000033', '`000121390025103497', '`000141057825000783', '`000091314425000009', '`000143774925004612', '`000182912625004113', '`000093041325001069', '`000121390025035604', '`000008596125000032', '`000000684525000049', '`000157791625000011', '`000071578725000006', '`000162828025011831', '`000160402825000012', '`000143774925029761', '`000119312525158722', '`000121390025026215', '`000092480525000012', '`000157587225000393', '`000162828025033105', '`000141057825000689', '`000105350725000025', '`000152013825000162', '`000151717525000002', '`000141057825001475', '`000182912625003270', '`000165495425012195', '`000095017025024750', '`000071742325000006', '`000000497725000047', '`000088461425000053', '`000005125325000013', '`000199771125000030', '`000117891325001126', '`000134287425000024', '`000144889325000009', '`000095017025070268', '`000190144025000012', '`000100683725000021', '`000107137125000053', '`000111505525000042']
4: ['`000009212225000018', '`000155837025003413', '`000007736025000006', '`000121390025041556', '`000119312525118506', '`000155837025002409', '`000121390025037703', '`000095017025099742', '`000141057825000623', '`000155837025011776', '`000000248825000012', '`000008943925000010', '`000004021125000024', '`000007628225000013', '`000089707725000007', '`000121390025103497', '`000119312525284680', '`000141057825000783', '`000130696525000007', '`000091314425000009', '`000143774925004612', '`000182912625004113', '`000007528825000033', '`000164841625000027', '`000093041325001069', '`000121390025035604', '`000008596125000032', '`000162828025011831', '`000000684525000049', '`000071578725000006', '`000157791625000011', '`000160402825000012', '`000143774925029761', '`000119312525158722', '`000095017025020763', '`000121390025026215', '`000095017025047918', '`000157587225000393', '`000092480525000012', '`000162828025033105', '`000141057825000689', '`000152013825000162', '`000095017025024750', '`000165495425012195', '`000141057825001475', '`000110465925104454', '`000101376225003608', '`000151717525000002', '`000105350725000025', '`000150446125000014', '`000182912625003270', '`000071742325000006', '`000000497725000047', '`000088461425000053', '`000005125325000013', '`000199771125000030', '`000117891325001126', '`000134287425000024', '`000144889325000009', '`000095017025070268', '`000190144025000012', '`000100683725000021', '`000107137125000053', '`000111505525000042']
3: ['`000129281425001504', '`000155837025002417', '`000138119725000036', '`000165495425004306', '`000149315225009391', '`000121390025021907', '`000000684525000049', '`000095017025047918', '`000152013825000162', '`000165495425012195', '`000182912625003270', '`000164117225001513', '`000071742325000006', '`000005125325000013', '`000199771125000030', '`000190144025000012', '`000143774925007559', '`000157791625000011', '`000111505525000042', '`000078332425000008', '`000000248825000012', '`000182912625004113', '`000071578725000006', '`000157587225000393', '`000101376225003608', '`000151717525000002', '`000150446125000014', '`000100683725000021', '`000009212225000018', '`000132046125000033', '`000121390025041556', '`000119312525118506', '`000155837025002409', '`000121390025037703', '`000191565725000019', '`000089707725000007', '`000119312525284680', '`000143774925004612', '`000093041325001069', '`000121390025035604', '`000160402825000012', '`000143774925029761', '`000119312525158722', '`000091114725000010', '`000121390025026215', '`000162828025033105', '`000105350725000025', '`000134287425000024', '`000144889325000009', '`000107137125000053', '`000155837025003413', '`000007736025000006', '`000141057825000623', '`000095017025099742', '`000155837025011776', '`000008943925000010', '`000004021125000024', '`000007628225000013', '`000121390025103497', '`000007528825000033', '`000141057825000783', '`000091314425000009', '`000164841625000027', '`000008596125000032', '`000162828025011831', '`000117184325007594', '`000092480525000012', '`000141057825000689', '`000095017025024750', '`000141057825001475', '`000110465925104454', '`000000497725000047', '`000088461425000053', '`000129281425001352', '`000095017025047901', '`000117891325001126', '`000095017025070268', '`000132440425000006', '`000003696625000024']
2: ['`000162828025008128', '`000142322125000100', '`000095017025042908', '`000162828025007110', '`000094667325000008', '`000129281425001504', '`000155837025002417', '`000138119725000036', '`000165495425004306', '`000149315225009391', '`000121390025021907', '`000000684525000049', '`000112336025000011', '`000164117225004712', '`000095017025047918', '`000152013825000162', '`000165495425012195', '`000182912625003270', '`000164117225001513', '`000071742325000006', '`000005125325000013', '`000199771125000030', '`000102891825000014', '`000190144025000012', '`000143774925007559', '`000111505525000042', '`000162828025007126', '`000106770125000008', '`000157791625000011', '`000078332425000008', '`000000248825000012', '`000162828025008401', '`000095017025059532', '`000182912625004113', '`000102085925000054', '`000071578725000006', '`000120717925000005', '`000157587225000393', '`000101376225003608', '`000151717525000002', '`000150446125000014', '`000143757825000007', '`000100683725000021', '`000009212225000018', '`000095017025026655', '`000132046125000033', '`000121390025041556', '`000143774925005687', '`000119312525118506', '`000155837025002409', '`000121390025037703', '`000110465925121185', '`000118518525000229', '`000191565725000019', '`000089707725000007', '`000119312525284680', '`000130696525000007', '`000143774925004612', '`000093041325001069', '`000121390025035604', '`000104013025000072', '`000110465925108504', '`000160402825000012', '`000143774925029761', '`000119312525158722', '`000091114725000010', '`000121390025026215', '`000093905725000242', '`000162828025033105', '`000105350725000025', '`000165495425012190', '`000134287425000024', '`000144889325000009', '`000107137125000053', '`000155837025003413', '`000007736025000006', '`000095017025099742', '`000141057825000623', '`000155837025011776', '`000181838325000022', '`000008943925000010', '`000004021125000024', '`000007628225000013', '`000121390025103497', '`000141057825000783', '`000007528825000033', '`000091314425000009', '`000137895025000036', '`000164841625000027', '`000032001725000011', '`000008596125000032', '`000162828025011831', '`000117184325007594', '`000171126925000004', '`000095017025078416', '`000084405925000009', '`000092480525000012', '`000141057825000689', '`000095017025024750', '`000110465925104454', '`000000497725000047', '`000118518525000706', '`000088461425000053', '`000095017025047901', '`000093570325000015', '`000121390025043484', '`000095017025070268', '`000141057825001050', '`000003696625000024']